<?php
header('Content-Type: text/html; charset=utf-8');
// A sessão precisa ser iniciada em cada página diferente
if (!isset($_SESSION)) session_start();


// Verifica se não há a variável da sessão que identifica o usuário
if ($_SESSION['codigoPer'] <> 'A') {
	// Destrói a sessão por segurança
	session_destroy();
	// Redireciona o visitante de volta pro login
	header("Location: index.php"); exit;
}
  $v_params = $this->getParams();
  $v_mensalidades= $v_params['v_mensalidades'];
  ?>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap Core CSS - Uses
        Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
        <link href="template/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="template/css/freelancer.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="template/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
        queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file://
        -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link href="template/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="template/js/fileinput.min.js" type="text/javascript"></script>
        <script src="template/js/fileinput_locale_pt-BR.js" type="text/javascript"></script>
        <script type="text/javascript" src="template/js/ajaxupload.3.5.js" ></script>
        <link rel="stylesheet" type="text/css" href="template/css/upload.css" />
        <script src="template/js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="template/js/jquery.mask.min.js"></script>
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
         <link href="template/bootstrap-datepicker/css/bootstrap-datepicker3.css" rel="stylesheet">
		<script src="template/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="template/bootstrap-datepicker/locales/bootstrap-datepicker.pt-BR.min.js"></script>
        <script src="template/js/jquery.maskMoney.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="template/AdminLTE.min.css" />
        <style>
            body { padding-top: 120px; }
        </style>
        <script>
        function fncSelecionarEstadoOrigem(estado) {
             $('#cidade').load('views/listarCidade.php?estado='+estado.value);
        };
        
        function fncSelecionarEstadoDestino(estado) {
             $('#cidadeDestino').load('views/listarCidade.php?estado='+estado.value);
        };
        
        $(document).ready(function() {
            $('#btnPesquisar').click(function(){
                //alert('teste');
                fncJson(1);
            });
             $('#btnLimpar').click(function(){
                //alert('teste');
                $('#palavraChave').val('');
                $('#cidade').val(0);
                $('#estado').val(0);
                $('#dataInicio').val('');
                $('#dataFim').val('');
                $("input:radio").attr("checked", false);
                
                fncJson(1);
            });
        });
        
        $(document).ready(function() {
            fncJson(1); 
        });
        
        function fncJson(pagina) {
            //alert(pagina);    
            var request = $.ajax({
                url: "./views/controlarMensalidade.php",
                beforeSend: function(){
                      $('#loading').html("<img src='template/img/loading.gif'/>").fadeIn('fast');
                },
                type: "POST",           
                dataType: "json",
                data: {"dataini":$('#dataInicio').val(),
                "datafim":$('#dataFim').val(), "tb_status":$('input[name="myRadio"]:checked', '#myForm').val(),"tb_statusAcesso":$('input[name="myRadioS"]:checked', '#myForm2').val(),
                "cidade":$('#cidade option:selected').val(), "estado":$('#estado option:selected').val(),
                "palavraChave":$('#palavraChave').val(), pagina}
            });
            request.done(function(data) {
                //alert('teste');
                //$("#tabela").html(data);
                $('#loading').fadeOut('fast');
                for($i=0; $i < data.length; $i++){
                    $("#tabela").html(data[$i]);    
                }
                $("#tabela").focus();
            });

            request.fail(function(jqXHR, textStatus) {
                alert( "Erro (Ajax - listar transporte): " + textStatus );
            });
        };
        
        function fncBloquearAcesso()
        {
            //alert($('#tb_pessoa_idPesBlo').val());
            var tb_pessoa_idPesBlo = $('#tb_pessoa_idPesBlo').val(); 
            //alert(tb_pessoa_idPesBlo);
            window.location.href = "?controle=Pessoa&acao=bloquearAcesso&idPes=" + tb_pessoa_idPesBlo;
        }
        
        
        function fncLiberarAcesso()
        {
            //alert($('#tb_pessoa_idPesLib').val());
            var tb_pessoa_idPesLib = $('#tb_pessoa_idPesLib').val(); 
            //alert(tb_pessoa_idPesLib);
            window.location.href = "?controle=Pessoa&acao=liberarAcesso&idPes=" + tb_pessoa_idPesLib;
        }
        
        /*function fncBaixaMensalidade()
        {
            //alert($('#idMensaBai').val());
            var idMensaBai = $('#idMensaBai').val(); 
            //alert(idMensaBai);
            window.location.href = "?controle=Mensalidade&acao=mensalidadeTransportador&idMensa=" + idMensaBai;
        }*/
        
        function fncDeletarMensalidade()
        {
            //alert($('#idMensaDel').val());
            var idMensaDel = $('#idMensaDel').val(); 
            //alert(idMensaDel);
            window.location.href = "?controle=Mensalidade&acao=apagarMensalidade&idMensa=" + idMensaDel;
        }
        
        
    </script>
    </head>
  
     <?php require 'template/header.php'; ?>

    <body id="page-top">
   	<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul class="breadcrumb">
              <li>
                <a href="?controle=Index&acao=Index">Home</a>
              </li>
              <li>
                <a href="?controle=Pessoa&acao=areaAdministrador">Área do Administrador</a> 
              </li>
               <li class="active">
               Controle de Mensalidade
            </ul>
          </div>
        </div>
      </div>
    </div>
	  <div class="section">
      <div class="container">
      	   		 <div class="row">
                    <div class="col-md-12">
                        <h1 class="text-center"> 
               				Controle de Mensalidades
				 		</h1>
                    </div>
                </div>
           <div class="row">
            <div class="col-md-6">
            <label class="control-label" for="lblDataRetirada">Período da data de vecimento</label><br>               
                                <div class="row">
                                    <div class="col-xs-12 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <div class="input-group date ">
                                                <input type="text" class="form-control" id='dataInicio' name='dataInicio' 
                                                data-validation-required-message="Por favor selecione uma data da coleta do transporte" value="<?php echo  isset($_SESSION['dataini']) ? $_SESSION['dataini'] : ''; ?>"
                                                placeholder="Data Inicial" readonly="" required="" tabindex="3"><span class="input-group-addon">
                                                <i class="glyphicon glyphicon-th"></i></span>
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                    </div>

                                     <div class="col-xs-12 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <div class="input-group date ">
                                                <input type="text" class="form-control" id='dataFim' name='dataFim' 
                                                data-validation-required-message="Por favor selecione uma data da coleta do transporte" value="<?php echo  isset($_SESSION['datafim']) ? $_SESSION['datafim'] : ''; ?>"
                                                placeholder="Data Final" readonly="" required="" tabindex="3"><span class="input-group-addon">
                                                <i class="glyphicon glyphicon-th"></i></span>
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
           <div class="form-group">
              <label class="control-label" for="exampleInputPassword1">Estado</label>
                <select class="form-control" name='estado' id='estado' onChange="fncSelecionarEstadoOrigem(this)">
                <option value="0">Estado</option>
                <?php
                    $o_estado = new EstadoModel();
                    $v_estados = $o_estado->_list();
                    $estado = isset($_SESSION['estado']) ? $_SESSION['estado'] : 'null';
                    foreach($v_estados AS $o_estado)
                    {
                    ?>
                        <option value="<?php echo $o_estado->getIdEst()?>" <?php echo $o_estado->getIdEst() == $estado ? 'selected' : '' ?>><?php echo $o_estado->getUfEst()?></option>
                <?php
                    }
                    ?>
                </select>
            </div>
            <div class="form-group" draggable="true">
              <label class="control-label" for="exampleInputEmail1">Cidade</label>
                    <select class="form-control" name='cidade' id='cidade'>
                    <option value="0">Cidade</option>
                           <?php
                                   $cidade = isset($_SESSION['cidade']) ? $_SESSION['cidade'] : 'null';
                                if ($cidade !== NULL)
                                    $cidade = $cidade;
                                else
                                    $cidade = 0;
                                $o_cidade = new CidadeModel();
                                $v_cidades = $o_cidade->_list($estado);
                                foreach($v_cidades AS $o_cidade)
                                {
                                ?>
                                    <option value="<?php echo $o_cidade->getIdCid()?>" <?php echo $o_cidade->getIdCid() == $cidade ? 'selected' : '' ?>><?php echo utf8_encode($o_cidade->getNomeCid())?></option>
                            <?php
                                }
                                ?>
                </select>
            </div>
            </div>
          <div class="col-md-6">
              
          <div class="form-group">
            <label class="control-label" for="exampleInputEmail1">Situação Da Mensalidade</label><br>
            <form id="myForm">
                    <?php
                    $o_situacaomensalidade = new SituacaoMensalidadeModel();
                    $v_situacaomensalidades = $o_situacaomensalidade->_list();
                    foreach($v_situacaomensalidades AS $o_situacaomensalidade)
                    {
                    ?>
                       <label>
                        <input type="radio" name="myRadio" value="<?php echo $o_situacaomensalidade->getIdSit() ?>" <?php echo isset($_SESSION['status']) ? ($_SESSION['status'] == $o_situacaomensalidade->getIdSit())?'checked':'' : '' ?>/> <?php echo $o_situacaomensalidade->getDescricaoSit() ?>
                       </label>
                <?php
                    }
                    ?>
             </form>
         </div>
         <div class="form-group">
            <label class="control-label" for="exampleInputEmail1">Situação De Acesso</label><br>
            <form id="myForm2">
                    <?php
                    $o_status= new StatusModel();
                    $v_status = $o_status->_list();
                    foreach($v_status AS $o_status)
                    {
                    ?>
                       <label>
                        <input type="radio" name="myRadioS" value="<?php echo $o_status->getIdSta() ?>" <?php echo isset($_SESSION['statusAcesso']) ? ($_SESSION['statusAcesso'] == $o_status->getIdSta())?'checked':'' : '' ?>/> <?php echo $o_status->getNomeSta() ?>
                       </label>
                <?php
                    }
                    ?>
             </form>
         </div>
            
            <div class="form-group" draggable="true">
              <label class="control-label" for="exampleInputPassword1">Nome</label>
              <input class="form-control" id="palavraChave" placeholder="" value="<?php echo  isset($_SESSION['palavraChave']) ? $_SESSION['palavraChave'] : ''; ?>">
            </div>
            
            <div class="form-group" draggable="true">
                <a class="btn btn-primary" id="btnPesquisar">Pesquisar</a>
                <a class="btn btn-danger" id="btnLimpar">Limpar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    
        <div class="section">
            <div class="container">
                <div class="row">
                     <div class="col-md-12" id="tabela">
            
                     </div>
                        <div class='text-center'>
                        <a href="?controle=Pessoa&acao=areaAdministrador" type="button" class="btn btn-danger">Voltar</a>
                        </div>
                 </div>
              </div>
           </div>
  </body>
  
<!-- Modal -->
<div id="addBookDialog" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body text-center">
        <p>Tem certeza que deseja bloquear acesso desse Transportador?</p>
        <div class="form-group">
	  		<input type='hidden' id="tb_pessoa_idPesBlo" name='tb_pessoa_idPesBlo' value=''>
			<a class="btn btn-primary" id="btnSim"  data-dismiss="modal" onclick=fncBloquearAcesso();>Sim</a>
			<button type="button" class="btn btn-danger" data-dismiss="modal">Não</button>
	  	</div>
      </div>
      <div class="modal-footer">
      </div>
    </div>

  </div>
</div>

<!-- Modal -->
<div id="addBookDialog2" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body text-center">
        <p>Tem certeza que deseja liberar acesso desse Transportador?</p>
        <div class="form-group">
	  		<input type='hidden' id="tb_pessoa_idPesLib" name='tb_pessoa_idPesLib' value=''>
			<a class="btn btn-primary" id="btnSim"  data-dismiss="modal" onclick=fncLiberarAcesso();>Sim</a>
			<button type="button" class="btn btn-danger" data-dismiss="modal">Não</button>
	  	</div>
      </div>
      <div class="modal-footer">
      </div>
    </div>

  </div>
</div>

<!-- 
<div id="addBookDialog3" class="modal fade" role="dialog">
  <div class="modal-dialog">


    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body text-center">
        <p>Tem certeza que deseja dar baixa nessa mensalidade?</p>
        <div class="form-group">
	  		<input type='hidden' id="idMensaBai" name='idMensaBai' value=''>
			<a class="btn btn-primary" id="btnSim"  data-dismiss="modal" onclick=fncBaixaMensalidade();>Sim</a>
			<button type="button" class="btn btn-danger" data-dismiss="modal">Não</button>
	  	</div>
      </div>
      <div class="modal-footer">
      </div>
    </div>

  </div>
</div>
-->

<!-- Modal -->
<div id="addBookDialog4" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body text-center">
        <p>Tem certeza que deseja  deletar essa mensalidade?</p>
        <div class="form-group">
	  		<input type='hidden' id="idMensaDel" name='idMensaDel' value=''>
			<a class="btn btn-primary" id="btnSim"  data-dismiss="modal" onclick=fncDeletarMensalidade();>Sim</a>
			<button type="button" class="btn btn-danger" data-dismiss="modal">Não</button>
	  	</div>
      </div>
      <div class="modal-footer">
      </div>
    </div>

  </div>
</div>
  
  
	<div id="myModal1" class="modal fade reply-sure" role="dialog">
			<div class="modal-dialog">
							    <!-- Modal content-->	
				<div class="modal-content">
					<div class="text-center">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title">Sucesso</h4>
					</div>
					</div>
					<div class="text-center">
					<div class="modal-body">
						<p>O Acesso foi bloquado com sucesso.</p>
					 </div>
					 </div>
					<div class="text-center">
					<div class="modal-footer-center">
					 	<button type="submit" class="btn btn-primary" data-number="1" data-dismiss="modal" id="btnCanOk" name="btnCanOk">OK</button>
						<br>
						<br>
						<br>		      	
					</div>
					</div>
				</div>			
			</div>
		</div>
		
			<div id="myModal2" class="modal fade reply-sure" role="dialog">
			<div class="modal-dialog">
							    <!-- Modal content-->	
				<div class="modal-content">
					<div class="text-center">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title">Sucesso</h4>
					</div>
					</div>
					<div class="text-center">
					<div class="modal-body">
						<p>O acesso foi liberado com sucesso.</p>
					 </div>
					 </div>
					<div class="text-center">
					<div class="modal-footer-center">
					 	<button type="submit" class="btn btn-primary" data-number="1" data-dismiss="modal" id="btnCanOk" name="btnCanOk">OK</button>
						<br>
						<br>
						<br>		      	
					</div>
					</div>
				</div>			
			</div>
		</div>
		
			<div id="myModal3" class="modal fade reply-sure" role="dialog">
			<div class="modal-dialog">
							    <!-- Modal content-->	
				<div class="modal-content">
					<div class="text-center">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title">Sucesso</h4>
					</div>
					</div>
					<div class="text-center">
					<div class="modal-body">
						<p>A baixa foi efetuada com sucesso.</p>
					 </div>
					 </div>
					<div class="text-center">
					<div class="modal-footer-center">
					 	<button type="submit" class="btn btn-primary" data-number="1" data-dismiss="modal" id="btnCanOk" name="btnCanOk">OK</button>
						<br>
						<br>
						<br>		      	
					</div>
					</div>
				</div>			
			</div>
		</div>
		
			<div id="myModal4" class="modal fade reply-sure" role="dialog">
			<div class="modal-dialog">
							    <!-- Modal content-->	
				<div class="modal-content">
					<div class="text-center">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title">Sucesso</h4>
					</div>
					</div>
					<div class="text-center">
					<div class="modal-body">
						<p>A mensalidade foi excluida com sucesso.</p>
					 </div>
					 </div>
					<div class="text-center">
					<div class="modal-footer-center">
					 	<button type="submit" class="btn btn-primary" data-number="1" data-dismiss="modal" id="btnCanOk" name="btnCanOk">OK</button>
						<br>
						<br>
						<br>		      	
					</div>
					</div>
				</div>			
			</div>
		</div>
  
  	<div id="myModal5" class="modal fade reply-sure" role="dialog">
			<div class="modal-dialog">
							    <!-- Modal content-->	
				<div class="modal-content">
					<div class="text-center">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title">Sucesso</h4>
					</div>
					</div>
					<div class="text-center">
					<div class="modal-body">
						<p>A mensalidade foi gerada com sucesso.</p>
					 </div>
					 </div>
					<div class="text-center">
					<div class="modal-footer-center">
					 	<button type="submit" class="btn btn-primary" data-number="1" data-dismiss="modal" id="btnCanOk" name="btnCanOk">OK</button>
						<br>
						<br>
						<br>		      	
					</div>
					</div>
				</div>			
			</div>
		</div>
		
	<div id="popupModal2" class="modal hide fade" tabindex="-1" role="dialog">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">×</button>
			<h3>Title</h3>
	</div>
	<div class="modal-body">
      <iframe src="" style="zoom:0.60" frameborder="0" height="250" width="99.6%"></iframe>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal">OK</button>
	</div>
</div>
		
	<div id="myModal6" class="modal hide fade" tabindex="-1" role="dialog">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3>Title</h3>
		</div>
		<div class="modal-body">
      		<iframe src="" style="zoom:0.60" frameborder="0" height="250" width="99.6%"></iframe>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal">OK</button>
		</div>
		</div>
  <br>
  <br>
  	<script>
		var targetParam = "<?php  echo $_GET['variavel'];  ?>";
		if (targetParam == 'bloqueado') {
			$(document).ready(function() {
				$('#myModal1').modal();
			});
		};
		
		if (targetParam == 'liberado') {
			$(document).ready(function() {
				$('#myModal2').modal();
			});
		};	
		
		if (targetParam == 'baixa') {
			$(document).ready(function() {
				$('#myModal3').modal();
			});
		};
		
		if (targetParam == 'excluido') {
			$(document).ready(function() {
				$('#myModal4').modal();
			});
		};
		
		if (targetParam == 'gerada') {
			$(document).ready(function() {
				$('#myModal5').modal();
			});
		};
		
	
		
	</script>
  
  <script>
 
	$(document).on("click", ".open-AddBookDialog", function () {
		 //alert(tb_pessoa_idPesBlo);
	     var tb_pessoa_idPesBlo = $(this).data('id');
	     //alert(tb_pessoa_idPesBlo);
	     $(".modal-body #tb_pessoa_idPesBlo").val( tb_pessoa_idPesBlo );
	});
	
	$(document).on("click", ".open-AddBookDialog2", function () {
		 //alert(tb_pessoa_idPesLib);
	     var tb_pessoa_idPesLib = $(this).data('id');
	     //alert(tb_pessoa_idPesLib);
	     $(".modal-body #tb_pessoa_idPesLib").val( tb_pessoa_idPesLib );
	});
	
	$(document).on("click", ".open-AddBookDialog3", function () {
		 //alert(idMensaBai);
	     var idMensaBai = $(this).data('id');
	     //alert(idMensaBai);
	     $(".modal-body #idMensaBai").val( idMensaBai );
	});
	
	$(document).on("click", ".open-AddBookDialog4", function () {
		 //alert(idMensaDel);
	     var idMensaDel = $(this).data('id');
	     //alert(idMensaDel);
	     $(".modal-body #idMensaDel").val( idMensaDel );
	});

	</script>
    <script>
          $('.input-group.date').datepicker({
                    format: "dd-mm-yyyy",
                    todayBtn: "linked",
                    autoclose: true,
                    todayHighlight: true,
                    language: "pt-BR",
                    showButtonPanel: true,
                closeText: 'Clear'
                    });
                    
    </script>
  
<?php require 'template/footer.php'; ?>
</html>
			