<?php
$v_params = $this->getParams();
$v_mensagens = $v_params['v_mensagens'];
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>
			Mensagem
		</title>
		<link rel="stylesheet" type="text/css" href="template/css/default.css" />
	</head>
<body>
	<div align="center">
		<table class='table_list' width="80%">
			<tr>
				<th>
					ID
				</th>
				<th>
					Remetente
				</th>
					<th>
					Destinatario
				</th>
				<th>
					Data Recebida
				</th>
				<th>
					Data Envio
				</th>
				<th>
					Assunto 
				</th>
				<th>
					Descrição
				</th>
				<th>
					Transportador
				</th>
				<th>
					Cliente
				</th>
				<th>
					Transporte
				</th>
				<th colspan="3">
					A&ccedil;&otilde;es
				</th>
			</tr>
			<?php
			foreach($v_mensagens AS $o_mensagem)
			{
				?>
				<tr>
					<td>
						<?php echo $o_mensagem->getIdMen()?>
					</td>
					<td>
						<?php echo $o_mensagem->getRemententeMen()?>
					</td>
					<td>
						<?php echo $o_mensagem->getDestinatarioMen()?>
					</td>
						<td>
						<?php echo $o_mensagem->getDataRecebidaMen()?>
					</td>
					<td>
						<?php echo $o_mensagem->getDataEnvioMen()?>
					</td>
					<td>
						<?php echo $o_mensagem->getAssuntoMen()?>
					</td>
						<td>
						<?php echo $o_mensagem->getDescricaoMen()?>
					</td>
					<td>
						<?php echo $o_mensagem->getTb_transportador_idTran()?>
					</td>
					<td>
						<?php echo $o_mensagem->getTb_cliente_idCli()?>
					</td>
					<td>
						<?php echo $o_mensagem->getTb_transporte_idTransp()?>
					</td>
					<td align="center">
						<a href='?controle=Mensagem&acao=manterMensagem&idMen=<?php echo $o_mensagem->getIdMen()?>' class='bt_blue'>Editar</a>
					</td>
					<td align="center">
						<a href='?controle=Mensagem&acao=apagarMensagem&idMen=<?php echo $o_mensagem->getIdMen()?>' class='bt_red'>Apagar</a>
					</td>
				</tr>
				<?php
			}
			?>
		</table>
		<br />
		<a href='?controle=Mensagem&acao=manterMensagem' class='bt_green'>Novo</a>
	</div>
</body>
</html>