<?php
header('Content-Type: text/html; charset=utf-8');
// A sessão precisa ser iniciada em cada página diferente
if (!isset($_SESSION)) session_start();

// Verifica se não há a variável da sessão que identifica o usuário
if ($_SESSION['codigoPer'] <> 'A') {
    // Destrói a sessão por segurança
    session_destroy();
    // Redireciona o visitante de volta pro login
    header("Location: index.php"); exit;
}
$v_params = $this->getParams();
$v_logs = $v_params['v_resposta_pesquisa'];
?>
<html>   
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap Core CSS - Uses
        Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
        <link href="template/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="template/css/freelancer.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="template/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
        queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file://
        -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link href="template/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="template/js/fileinput.min.js" type="text/javascript"></script>
        <script src="template/js/fileinput_locale_pt-BR.js" type="text/javascript"></script>
        <script type="text/javascript" src="template/js/ajaxupload.3.5.js" ></script>
        <link rel="stylesheet" type="text/css" href="template/css/upload.css" />
        <script src="template/js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="template/js/jquery.mask.min.js"></script>
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
         <link rel="stylesheet" type="text/css" href="template/css/datepicker.css">
        <script src="template/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="template/js/locales/bootstrap-datepicker.pt-BR.js"></script>
        <script src="template/js/jquery.maskMoney.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="template/AdminLTE.min.css" />
    <script>
        $(document).ready(function() {
            fncJson(1); 
        });
        
        function fncJson(pagina) {
            //alert(pagina);    
            var request = $.ajax({
                url: "./views/listarRespostaPesquisa.php",
                type: "POST",           
                dataType: "json"
            });
            request.done(function(data) {
               // $("#tabela").html(data);
                for($i=0; $i < data.length; $i++){
                    $("#tabela").html(data[$i]);    
                }
                $("#tabela").focus();
            });

            request.fail(function(jqXHR, textStatus) {
                alert( "Erro (Ajax - listar transporte): " + textStatus );
            });
        };
        
    </script>
        <style>
            body { padding-top: 120px; }
        </style>
    </head>
    <?php require 'template/header.php'; ?>

    <body id="page-top">
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul class="breadcrumb">
              <li>
                <a href="?controle=Index&acao=Index">Home</a>
              </li>
              <li>
                <a href="?controle=Pessoa&acao=areaAdministrador">Área do Administrador</a> 
              </li>
               <li class="active">
                Respostas da Pesquisa 
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
       <div class="section">
      <div class="container">
                 <div class="row">
                    <div class="col-md-12">
                        <h1 class="text-center">Respostas da Pesquisa</h1>
                    </div>
                </div>

      </div>
    </div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                      <h4>
    <span>
      <i class="fa fa-bar-chart-o"></i></span>Pesquisa
  </h4>
  <div>
    <h5>
      <em>Como conheceu a Savicki?</em>
    </h5>
                      <div class="col-md-12" id="tabela">
            
                      </div>
  
  </div>
                                <div class="text-center">
                                    <td align="center">
                                        <a href="?controle=Pessoa&acao=areaAdministrador"
                                        class="btn btn-danger">Voltar</a>
                                    </td>
                                </div>
                    </div>
                </div>
            </div>
        </div>
        
  </body>

<?php require 'template/footer.php'; ?>
</html>

