<?php
header('Content-Type: text/html; charset=utf-8');
// A sessão precisa ser iniciada em cada página diferente
if (!isset($_SESSION)) session_start();

// Verifica se não há a variável da sessão que identifica o usuário
if ($_SESSION['codigoPer'] <> 'A') {
	// Destrói a sessão por segurança
	session_destroy();
	// Redireciona o visitante de volta pro login
	header("Location: index.php"); exit;
}
$v_params = $this->getParams();
$v_pessoas = $v_params['v_pessoas'];
?>
<html>    
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap Core CSS - Uses
        Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
        <link href="template/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="template/css/freelancer.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="template/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
        queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file://
        -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link href="template/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="template/js/fileinput.min.js" type="text/javascript"></script>
        <script src="template/js/fileinput_locale_pt-BR.js" type="text/javascript"></script>
        <script type="text/javascript" src="template/js/ajaxupload.3.5.js" ></script>
        <link rel="stylesheet" type="text/css" href="template/css/upload.css" />
        <script src="template/js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="template/js/jquery.mask.min.js"></script>
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <link href="template/bootstrap-datepicker/css/bootstrap-datepicker3.css" rel="stylesheet">
		<script src="template/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="template/bootstrap-datepicker/locales/bootstrap-datepicker.pt-BR.min.js"></script>
        <script src="template/js/jquery.maskMoney.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="template/AdminLTE.min.css" />
          <style>
            body { padding-top: 120px; }
        </style>
    </head>
    <script>
    	function fncSelecionarEstadoOrigem(estado) {
			 $('#cidade').load('views/listarCidade.php?estado='+estado.value);
		};
		
		function fncSelecionarEstadoDestino(estado) {
			 $('#cidade').load('views/listarCidade.php?estado='+estado.value);
		};
     $(document).ready(function() {
			$('#btnPesquisar').click(function(){
				//alert('teste');
				fncJson(1);
			});
			 $('#btnLimpar').click(function(){
                //alert('teste');
                $('#palavraChave').val('');
                $('#cidade').val(0);
                $('#estado').val(0);
                $('#dataInicio').val('');
                $('#dataFim').val('');
                
                fncJson(1);
            });
		});
		
		$(document).ready(function() {
			fncJson(1);	
		});
		
		function fncJson(pagina) {
			//alert(pagina);	
			var request = $.ajax({
				url: "./views/listarTransportador.php",
				type: "POST",			
				dataType: "json",
				data: {"status":$('#status').val(),"palavraChave":$('#palavraChave').val(), "pagina":pagina,
				"dataini":$('#dataInicio').val(),
				"cidade":$('#cidade').val(),
				"estado":$('#estado').val(),
				"datafim":$('#dataFim').val()}
			});
			request.done(function(data) {
				//alert('teste');
			    //$("#tabela").html(data);
				for($i=0; $i < data.length; $i++){
					$("#tabela").html(data[$i]);	
				}
				$("#tabela").focus();
			});

			request.fail(function(jqXHR, textStatus) {
				alert( "Erro (Ajax - listar transporte): " + textStatus );
			});
		};
    </script>
    
    <?php require 'template/header.php'; ?>

    <body id="page-top">
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul class="breadcrumb">
              <li>
                <a href="?controle=Index&acao=Index">Home</a>
              </li>
              <li>
                <a href="?controle=Pessoa&acao=areaAdministrador">Área do Administrador</a> 
              </li>
               <li class="active">
               lista de Transportadores
            </ul>
          </div>
        </div>
      </div>
    </div>
       <div class="section">
      <div class="container">
      	   		 <div class="row">
                    <div class="col-md-12">
                        <h1 class="text-center"> 
                		Lista de Transportadores
				 		</h1>
                    </div>
                </div>
        <div class="row">
            <div class="col-md-6">
			<label class="control-label" for="lblDataRetirada">Período da data de cadastro</label><br>               
                                <div class="row">
                                    <div class="col-xs-12 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <div class="input-group date ">
                                                <input type="text" class="form-control" id='dataInicio' name='dataInicio' 
                                                data-validation-required-message="Por favor selecione uma data da coleta do transporte" value="<?php echo  isset($_SESSION['dataini']) ? $_SESSION['dataini'] : ''; ?>"
                                                placeholder="Data Inicial" readonly="" required="" tabindex="3"><span class="input-group-addon">
                                                <i class="glyphicon glyphicon-th"></i></span>
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                    </div>

                                     <div class="col-xs-12 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <div class="input-group date ">
                                                <input type="text" class="form-control" id='dataFim' name='dataFim' 
                                                data-validation-required-message="Por favor selecione uma data da coleta do transporte" value="<?php echo  isset($_SESSION['datafim']) ? $_SESSION['datafim'] : ''; ?>"
                                                placeholder="Data Final" readonly="" required="" tabindex="3"><span class="input-group-addon">
                                                <i class="glyphicon glyphicon-th"></i></span>
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
           <div class="form-group">
              <label class="control-label" for="exampleInputPassword1">Estado</label>
				<select class="form-control" name='estado' id='estado' onChange="fncSelecionarEstadoOrigem(this)">
				<option value="0">Estado</option>
				<?php
					$o_estado = new EstadoModel();
					$v_estados = $o_estado->_list();
					foreach($v_estados AS $o_estado)
					{
					?>
						<option value="<?php echo $o_estado->getIdEst()?>"><?php echo $o_estado->getUfEst()?></option>
				<?php
					}
					?>
				</select>
            </div>
            <div class="form-group" draggable="true">
              <label class="control-label" for="exampleInputEmail1">Cidade</label>
					<select class="form-control" name='cidade' id='cidade'>
					<option value="0">Cidade</option>
				</select>
            </div>
            </div>
          <div class="col-md-6">
            
            
            <div class="form-group" draggable="true">
              <label class="control-label" for="exampleInputPassword1">Nome</label>
              <input class="form-control" id="palavraChave" placeholder="">
            </div>
			
            <div class="form-group" draggable="true">
		  		<a class="btn btn-primary" id="btnPesquisar">Pesquisar</a>
		  		<a class="btn btn-danger" id="btnLimpar">Limpar</a>
			</div>
          </div>
        </div>
      </div>
    </div>
       <div class="section">
            <div class="container">
                <div class="row">
                     <div class="col-md-12" id="tabela">
            
                     </div>
                        <div class='text-center'>
                        <a href="?controle=Pessoa&acao=areaAdministrador" type="button" class="btn btn-danger">Voltar</a>
                        </div>
                 </div>
              </div>
           </div>
    </body>
    <br>
    <br>
        <div id="myModal1" class="modal fade" role="dialog">
			<div class="modal-dialog">
							    <!-- Modal content-->	
				<div class="modal-content">
					<div class="text-center">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title">Sucesso</h4>
					</div>
					</div>
					<div class="text-center">
					<div class="modal-body">
						<p>O Transportador foi editado com sucesso.</p>
					 </div>
					 </div>
					<div class="text-center">
					<div class="modal-footer-center">
					 	<button type="submit" class="btn btn-primary" data-dismiss="modal">OK</button>
						<br>
						<br>
						<br>		      	
					</div>
					</div>
				</div>			
			</div>
		</div>
		
                
       <script>
       var targetParam = "<?php  echo $_GET['variavel'];  ?>";
       	 if (targetParam == 'editado') {
			$(document).ready(function() {
				$('#myModal1').modal();
			});
		};
       </script> 
       
           <script>
            $('.input-group.date').datepicker({
                    format: "dd-mm-yyyy",
                    todayBtn: "linked",
                    autoclose: true,
                    todayHighlight: true,
                    language: "pt-BR",
                    showButtonPanel: true,
                closeText: 'Clear'
                    });
                    
            </script>
    <?php require 'template/footer.php'; ?>
</html>