<?php
header('Content-Type: text/html; charset=utf-8');
// A sessão precisa ser iniciada em cada página diferente
if (!isset($_SESSION))
	session_start();

// Verifica se não há a variável da sessão que identifica o usuário
if ($_SESSION['codigoPer'] <> 'A') {
	// Destrói a sessão por segurança
	session_destroy();
	// Redireciona o visitante de volta pro login
	header("Location: index.php");
	exit ;
}
$v_params = $this -> getParams();
$v_logs = $v_params['v_logs'];
?>

<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- Bootstrap Core CSS - Uses
		Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
		<link href="template/css/bootstrap.min.css" rel="stylesheet">
		<!-- Custom CSS -->
		<link href="template/css/freelancer.css" rel="stylesheet">
		<!-- Custom Fonts -->
		<link href="template/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
		<link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
		<link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
		queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file://
		-->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
		<link href="template/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
		<script src="template/js/fileinput.min.js" type="text/javascript"></script>
		<script src="template/js/fileinput_locale_pt-BR.js" type="text/javascript"></script>
		<script type="text/javascript" src="template/js/ajaxupload.3.5.js" ></script>
		<link rel="stylesheet" type="text/css" href="template/css/upload.css" />
		<script src="template/js/jquery.validate.min.js"></script>
		<script type="text/javascript" src="template/js/jquery.mask.min.js"></script>
		<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
		<script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
		<link href="template/bootstrap-datepicker/css/bootstrap-datepicker3.css" rel="stylesheet">
		<script src="template/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="template/bootstrap-datepicker/locales/bootstrap-datepicker.pt-BR.min.js"></script>
		<script src="template/js/jquery.maskMoney.js" type="text/javascript"></script>
		<link rel="stylesheet" type="text/css" href="template/AdminLTE.min.css" />
		<script>
			$(document).ready(function() {
				$('#btnPesquisar').click(function() {
					//alert('teste');
					fncJson(1);
				});
				$('#btnLimpar').click(function() {
					//alert('teste');
					$('#dataInicio').val('');
					$('#dataFim').val('');
					$('#palavraChave').val('');
					$("input:radio").attr("checked", false);

					fncJson(1);
				});
			});

			$(document).ready(function() {
				fncJson(1);
			});

			function fncJson(pagina) {
				//alert(pagina);
				var request = $.ajax({
					url : "./views/listarLog.php",
					type : "POST",
					dataType : "json",
					data : {
						"palavraChave" : $('#palavraChave').val(),
						"dataini" : $('#dataInicio').val(),
						"datafim" : $('#dataFim').val(),
						"idPer" : $('input[name="myRadio"]:checked', '#myForm').val(),
						"pagina" : pagina
					}
				});
				request.done(function(data) {
					//alert('teste');
					//$("#tabela").html(data);
					for ( $i = 0; $i < data.length; $i++) {
						$("#tabela").html(data[$i]);
					}
					$("#tabela").focus();
				});

				request.fail(function(jqXHR, textStatus) {
					alert("Erro (Ajax - listar log): " + textStatus);
				});
			};
		</script>
		<style>
			body {
				padding-top: 120px;
			}
		</style>
	</head>
	<?php
		require 'template/header.php';
	?>
	<body id="page-top">
		<div class="section">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<ul class="breadcrumb">
							<li>
								<a href="?controle=Index&acao=Index">Home</a>
							</li>
							<li>
								<a href="?controle=Pessoa&acao=areaAdministrador">Área do Administrador</a>
							</li>
							<li class="active">
								Lista de Logs
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="section">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1 class="text-center">Lista de Logs</h1>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group" draggable="true">
							<label class="control-label" for="exampleInputPassword1">Nome Usuário</label>
							<input class="form-control" id="palavraChave" placeholder="">
						</div>

						<label class="control-label" for="lblDataRetirada">Período da data de Log</label>
						<br>
						<div class="row">
							<div class="col-xs-12 col-sm-6 col-md-6">
								<div class="form-group">
									<div class="input-group date ">
										<input type="text" class="form-control" id='dataInicio' name='dataInicio'
										data-validation-required-message="Por favor selecione uma data"
										placeholder="Data Inicial" readonly="" required="" tabindex="3">
										<span class="input-group-addon"> <i class="glyphicon glyphicon-th"></i></span>
										<p class="help-block text-danger"></p>
									</div>
								</div>
							</div>

							<div class="col-xs-12 col-sm-6 col-md-6">
								<div class="form-group">
									<div class="input-group date ">
										<input type="text" class="form-control" id='dataFim' name='dataFim'
										data-validation-required-message="Por favor selecione uma data"
										placeholder="Data Final" readonly="" required="" tabindex="3">
										<span class="input-group-addon"> <i class="glyphicon glyphicon-th"></i></span>
										<p class="help-block text-danger"></p>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="col-md-6">

						<div class="form-group">
							<label class="control-label" for="exampleInputEmail1">Perfil</label>
							<br>
							<form id="myForm">
								<?php
$o_perfil = new PerfilModel();
$v_perfis = $o_perfil->_list();
foreach($v_perfis AS $o_perfil)
{
								?>
								<label >
									<input type="radio" name="myRadio" value="<?php echo $o_perfil->getIdPer()?>"/>
									<?php echo utf8_encode($o_perfil->getNomePer())?> </label>
								<?php
								}
								?>
							</form>
						</div>

						<div class="form-group" draggable="true">
							<a class="btn btn-primary" id="btnPesquisar">Pesquisar</a>
							<a class="btn btn-danger" id="btnLimpar">Limpar</a>
						</div>
					</div>

				</div>
			</div>
		</div>
		<div class="section">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="col-md-12" id="tabela">

						</div>
						<div class="text-center">
							<td align="center"><a href="?controle=Pessoa&acao=areaAdministrador"
							class="btn btn-danger">Voltar</a></td>
						</div>
					</div>
				</div>
			</div>
		</div>

		<script>
			$('.input-group.date').datepicker({
				format : "dd-mm-yyyy",
				todayBtn : "linked",
				autoclose : true,
				language : "pt-BR"
			});
		</script>

	</body>
	>
	<?php
		require 'template/footer.php';
	?>
</html>