<?php
// A sessão precisa ser iniciada em cada página diferente
if (!isset($_SESSION)) session_start();


// Verifica se não há a variável da sessão que identifica o usuário
if ($_SESSION['codigoPer'] <> 'T') {
	// Destrói a sessão por segurança
	session_destroy();
	// Redireciona o visitante de volta pro login
	header("Location: index.php"); exit;
}
  $v_params = $this->getParams();
  $v_mensalidades= $v_params['v_mensalidades'];
  ?>
 <html>   
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="template/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="template/js/fileinput.min.js" type="text/javascript"></script>
        <script src="template/js/fileinput_locale_pt-BR.js" type="text/javascript"></script>
    </head>
    <?php require 'template/header.php'; ?>

    <body id="page-top">
	  <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="text-center">Lista de Mensalidades</h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-bordered table-condensed table-hover table-striped">
                            <thead>
				  <tr>
					  <th>
						  ID
					  </th>
					  <th>
						  Data Vencimento
					  </th>
					  <th>
						  Data Pagamento
					  </th>
					  <th>
						  Valor
					  </th>
					  <th>
						  Situação
					  </th>
					  <th>
						  Transportador
					  </th>
					  <th>
						  Boleto
					  </th>
					  <th class="text-center" colspan="3">
						  A&ccedil;&otilde;es
					  </th>
				</tr>
			  </thead>
			  <tbody>
				  <?php
				  foreach($v_mensalidades AS $o_mensalidade)
				  {
					  ?>
					  <tr>
						  <td align="center">
							  <?php echo $o_mensalidade->getIdMensa()?>
						  </td>
						  <td align="center">
							  <?php echo date('d/m/Y', strtotime($o_mensalidade->getDataVencimentoMensa()))?>
						  </td>
						  <td align="center">
							  <?php if ($o_mensalidade->getDataPagamentoMensa() != NULL and $o_mensalidade->getDataPagamentoMensa() != '1900-01-01 00:00:00.000' )
							  	echo date('d/m/Y', strtotime($o_mensalidade->getDataPagamentoMensa()))
							  ?>
						  </td>
						  <td align="right">
							  <?php echo number_format($o_mensalidade->getValorMensa(), 2, ',', '.')?>
						  </td>
						  <td align="center">
							  <?php 
							  $o_situacaomensalidade = new SituacaoMensalidadeModel();
							  $o_situacaomensalidade->loadById($o_mensalidade->getTb_situacaoMensalidade_idSit());
							  echo $o_situacaomensalidade->getDescricaoSit();
							  ?>
						  </td>
						  <td>
							  <?php 
							  $o_transportador = new PessoaModel();
							  $o_transportador->loadById($o_mensalidade->getTb_pessoa_idPes());
							  echo $o_transportador->getPrimeiroNomePes();
							  ?>
						  </td>
						  <td align="center">
							  <a href="?controle=Boleto&acao=gerarBoleto&idMensa=<?php echo $o_mensalidade->getIdMensa()?>" id="pesqUsuario"><img src="template/images/icone-boleto.gif"></a>
						  </td>
						  <td align="center">
							  <a href='?controle=Mensalidade&acao=manterMensalidade&idMensa=<?php echo $o_mensalidade->getIdMensa()?>' class='btn btn-primary btn-lg''>Editar</a>
						  </td>
						  <td align="center">
							  <a href='?controle=Mensalidade&acao=apagarMensalidade&idMensa=<?php echo $o_mensalidade->getIdMensa()?>' class='btn btn-danger btn-lg''>Apagar</a>
						  </td>
					  </tr>
					  <?php
				  }?>
			  </tbody>
		</table>
                                    <td align="center">
                                        <a href="?controle=Mensalidade&acao=manterMensalidade"
                                        class="btn btn-success btn-lg">Nova</a>
                                    </td>
                    </div>
                </div>
            </div>
        </div>
              <script>
          $('.input-group.date').datepicker({
                    format: "dd-mm-yyyy",
                    todayBtn: "linked",
                    autoclose: true,
                    todayHighlight: true,
                    language: "pt-BR",
                    showButtonPanel: true,
                closeText: 'Clear'
                    });
                    
    </script>
  </body>
<?php require 'template/footer.php'; ?>
</html>
			