<?php
if (!isset($_SESSION)){
    	session_start();
    }
header('Content-Type: text/html; charset=utf-8');
$v_params = $this->getParams();
$v_avaliacoes = $v_params['v_avaliacoes'];
$opcao = isset($_GET['opcao']) ? $_GET['opcao'] : '';
$idPes = isset($_SESSION['idPes']) ? $_SESSION['idPes'] : '0';

?>
<!DOCTYPE html>
	    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap Core CSS - Uses
        Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
        <link href="template/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="template/css/freelancer.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="template/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
        queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file://
        -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link href="template/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="template/js/ajaxupload.3.5.js" ></script>
        <link rel="stylesheet" type="text/css" href="template/css/upload.css" />
        <script type="text/javascript" src="template/js/jquery.mask.min.js"></script>
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="template/js/jquery.validate.min.js"></script>
        <link href="template/bootstrap-datepicker/css/bootstrap-datepicker3.css" rel="stylesheet">
		<script src="template/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="template/bootstrap-datepicker/locales/bootstrap-datepicker.pt-BR.min.js"></script>
        <script src="template/js/jquery.maskMoney.js" type="text/javascript"></script>
        <script src="template/js/fileinput.min.js" type="text/javascript"></script>
        <script src="template/js/fileinput_locale_pt-BR.js" type="text/javascript"></script>
		<script>
		$(document).ready(function() {
			$('#btnPesquisar').click(function(){
				//alert('teste');
				fncJson(1);
			});
			 $('#btnLimpar').click(function(){
                //alert('teste');
                $('#dataInicio').val('');
                $('#dataFim').val('');
                $('#tb_categoria_idCat').val(0);
                $('#palavraChave').val('');
                
                fncJson(1);
            });
		});
		
		$(document).ready(function() {
			fncJson(1);	
		});
		
		function fncJson(pagina) {
			//alert(pagina);	
			var request = $.ajax({
				url: "./views/listarAvaliacao.php",
				beforeSend: function(){
		              $('#loading').html("<img src='template/img/loading.gif'/>").fadeIn('fast');
				},
				type: "POST",			
				dataType: "json",
				data: {"opcao":<?php echo '"'.$opcao.'"';?>, "dataini":$('#dataInicio').val(),
				"datafim":$('#dataFim').val(), "categoria":$('#tb_categoria_idCat').val(),
				"palavraChave":$('#palavraChave').val(), "pagina":pagina}
			});
			request.done(function(data) {
				//alert('teste');
			    //$("#tabela").html(data);
			    $('#loading').fadeOut('fast');
				for($i=0; $i < data.length; $i++){
					$("#tabela").html(data[$i]);	
				}
				//alert($('#dataFim').val());
				//alert($('#tb_categoria_idCat').val());
			});

			request.fail(function(jqXHR, textStatus) {
				alert( "Erro (Ajax - listar transporte): " + textStatus );
			});
		};	
		
		</script>
	
      <style>
            body { padding-top: 210px; }
        </style>
    </head>
 <?php require 'template/header.php'; ?>


<body>
	<div class="section" >
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul class="breadcrumb">
              <li>
                <a href="?controle=Index&acao=Index">Home</a>
              </li>
              <li>
              	<?php
              	if ($_SESSION['codigoPer'] == 'U' )
				{
				?>
                <a href="?controle=Pessoa&acao=areaCliente">Área do Cliente</a> 
                <?php
                }
				?>
				<?php
				if ($_SESSION['codigoPer'] == 'T' )
				{
				?>
                <a href="?controle=Pessoa&acao=areaTransportador">Área do Transportador</a> 
                 <?php
                }
				?>
              </li>
               <li class="active">
               <?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "clienteativos"  and $_SESSION['codigoPer'] == 'U')
				{
				?>
				Transportes Ativos
				<?php 
				}
				?>
			
				<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "clienteinativos")
				{
				?>
				Transportes Cancelados
				<?php 
				}
				?>
					<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "transpganhos")
				{
				?>
				Transportes Ganhos
				<?php 
				}
				?>
				<?php 
				if(isset($_GET['opcao']) and $_GET['opcao'] == "clienteativosTrans" and $_SESSION['codigoPer'] == 'T'){
					?>
                Pesquisar Transporte
               <?php
				}
				?>
				<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "transpAndamentoTrans")
				{
				?>
				Transportes em Andamento
				<?php 
				}
				?>
				
				<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "transpandamento")
				{
				?>
				Transportes em Andamento
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "transpconcluido")
				{
				?>
				Transportes Concluidos
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "transpConcluidoTrans")
				{
				?>
				Transportes Concluidos
				<?php 
				}
				?>
				    <?php
                if(isset($_GET['opcao']) and $_GET['opcao'] == "transpAvaliacoes")
                {
                ?>
                Avaliações Recebidas
                <?php 
                }
                ?>
				
				</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
	 <div class="section">
      <div class="container">
      	   		 <div class="row">
                    <div class="col-md-12">
                        <h1 class="text-center"> 
               Avaliações Recebidas 
				 </h1>
                    </div>
                </div>
        <div class="row">
            <div class="col-md-6">
            <div class="form-group">
              <label class="control-label" for="exampleInputEmail1">Categoria</label>
				<select class="form-control" name='tb_categoria_idCat' id='tb_categoria_idCat'>
				<option value="0">Categoria</option>
				<?php
					$o_categoria = new CategoriaModel();
                    $categoria = isset($_SESSION['categoria']) ? $_SESSION['categoria'] : 'null';
					$v_categorias = $o_categoria->_list();
					foreach($v_categorias AS $o_categoria)
					{
					?>
						<option value="<?php echo $o_categoria->getIdCat()?>" <?php if ($o_categoria->getIdCat() ==  $categoria) echo 'selected' ?>><?php echo $o_categoria->getNomeCat()?></option>
				<?php
					}
					?>
				</select>
            </div>
            
            
			<script src="http://cdn.jsdelivr.net/webshim/1.12.4/extras/modernizr-custom.js"></script>
			<!-- polyfiller file to detect and load polyfills -->
			<script src="http://cdn.jsdelivr.net/webshim/1.12.4/polyfiller.js"></script>
			<script>
			  webshims.setOptions('waitReady', false);
			  webshims.setOptions('forms-ext', {types: 'date'});
			  webshims.polyfill('forms forms-ext');
			</script>
			<label class="control-label" for="lblDataRetirada">Período da data de retirada</label><br>				
		        				<div class="row">
                                    <div class="col-xs-12 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <div class="input-group date ">
                                                <input type="text" class="form-control" id='dataInicio' name='dataInicio' 
                                                data-validation-required-message="Por favor selecione uma data da coleta do transporte" value="<?php echo  isset($_SESSION['dataini']) ? $_SESSION['dataini'] : ''; ?>"
                                                placeholder="Data Inicial" readonly="" required="" tabindex="3"><span class="input-group-addon">
                                                <i class="glyphicon glyphicon-th"></i></span>
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                    </div>

                                     <div class="col-xs-12 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <div class="input-group date ">
                                                <input type="text" class="form-control" id='dataFim' name='dataFim' 
                                                data-validation-required-message="Por favor selecione uma data da coleta do transporte" value="<?php echo  isset($_SESSION['datafim']) ? $_SESSION['datafim'] : ''; ?>"
                                                placeholder="Data Final" readonly="" required="" tabindex="3"><span class="input-group-addon">
                                                <i class="glyphicon glyphicon-th"></i></span>
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>

   
            </div>
          <div class="col-md-6">
			
            <div class="form-group" draggable="true">
              <label class="control-label" for="exampleInputPassword1">Descrição do Transporte</label>
              <input class="form-control" id="palavraChave" placeholder="">
            </div>
			<div id="centro"></div>
            <div class="form-group" draggable="true">
		  		<a class="btn btn-primary" id="btnPesquisar">Pesquisar</a>
		  		<a class="btn btn-danger" id="btnLimpar">Limpar</a>
			</div>
          </div>
        </div>
      </div>
    </div>
    <br>
    <br>
  	<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12" id="tabela">
		  </div>
			</div>
      </div>
    </div>
			    					
			                        <div class='text-center'>
                                       <?php
									   if($_SESSION['codigoPer'] == 'A')
									   {
									   ?>
							      	  <a href="?controle=Pessoa&acao=areaAdministrador" type="button" class="btn btn-danger" >Voltar</a>
							      	  <?php
									   }
									   ?>
									   	<?php
									   if($_SESSION['codigoPer'] == 'T')
									   {
									   ?>
							      	  <a href="?controle=Pessoa&acao=areaTransportador" type="button" class="btn btn-danger">Voltar</a>
							      	  <?php
									   }
									   ?>
									      	<?php
									   if($_SESSION['codigoPer'] == 'U')
									   {
									   ?>
							      	  <a href="?controle=Pessoa&acao=areaCliente" type="button" class="btn btn-danger">Voltar</a>
							      	  <?php
									   }
									   ?>
									   </div>
									   <br>
                                    <br>
    
    <script>
          $('.input-group.date').datepicker({
                    format: "dd-mm-yyyy",
                    todayBtn: "linked",
                    autoclose: true,
                    todayHighlight: true,
                    language: "pt-BR",
                    showButtonPanel: true,
                closeText: 'Clear'
                    });
                    
    </script>

</body>
 <?php require 'template/footer.php'; ?>
</html>

