<?php
header('Content-Type: text/html; charset=utf-8');
// A sessão precisa ser iniciada em cada página diferente
if (!isset($_SESSION)) session_start();

// Verifica se não há a variável da sessão que identifica o usuário
if ($_SESSION['codigoPer'] <> 'U') {
	// Destrói a sessão por segurança
	session_destroy();
	// Redireciona o visitante de volta pro login
	header("Location: index.php"); exit;
}
$tb_transporte_idTransp = isset($_GET['tb_transporte_idTransp']) ? $_GET['tb_transporte_idTransp'] : '';
$opcao = isset($_GET['opcao']) ? $_GET['opcao'] : '';
$idPes = isset($_SESSION['idPes']) ? $_SESSION['idPes'] : '0';
	
?>
<html>  
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap Core CSS - Uses
        Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
        <link href="template/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="template/css/freelancer.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="template/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
        queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file://
        -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link href="template/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="template/js/fileinput.min.js" type="text/javascript"></script>
        <script src="template/js/fileinput_locale_pt-BR.js" type="text/javascript"></script>
        <script type="text/javascript" src="template/js/ajaxupload.3.5.js" ></script>
		<link rel="stylesheet" type="text/css" href="template/css/upload.css" />
	  	<script src="template/js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="template/js/jquery.mask.min.js"></script>
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <link href="template/bootstrap-datepicker/css/bootstrap-datepicker3.css" rel="stylesheet">
		<script src="template/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="template/bootstrap-datepicker/locales/bootstrap-datepicker.pt-BR.min.js"></script>
        <script src="template/js/jquery.maskMoney.js" type="text/javascript"></script>
	    <script>
	    	$(document).ready(function() {
			$('#btnPesquisar').click(function(){
				//alert('teste');
				fncJson(1);
			});
			 $('#btnLimpar').click(function(){
                //alert('teste');
                $('#dataInicio').val('');
                $('#dataFim').val('');
                $('#palavraChave').val('');
                fncJson(1);
            });
		});
		
		$(document).ready(function() {
			fncJson(1);	
		});
		
		function fncJsonMensagem(idLan) {
			//alert(idLan);
			var request = $.ajax({
				url: "./views/verMensagemCli.php",
				beforeSend: function(){
		              $('#loading').html("<img src='template/img/loading.gif'/>").fadeIn('fast');
				},
				type: "POST",			
				dataType: "json",
				data: {"idLan":idLan}
			});
			request.done(function(data) {
				//alert('teste');
			    //$("#tabela").html(data);
			    //$('#loading').fadeOut('fast');
			
				 for($i=0; $i < data.length; $i++){
					$("#mensagemLance" + idLan).html(data[$i]);	
				}
				
			});

			request.fail(function(jqXHR, textStatus) {
				alert( "Erro (Ajax - listar transporte): " + textStatus );
			});
		};
		
	
		
		function fncJson(pagina) {
			//alert(pagina);	
			var request = $.ajax({
				url: "./views/listarMensagemCli.php",
				beforeSend: function(){
		              $('#loading').html("<img src='template/img/loading.gif'/>").fadeIn('fast');
				},
				type: "POST",			
				dataType: "json",
				data: {"opcao":<?php echo '"'.$opcao.'"';?>,"tb_transporte_idTransp":<?php echo '"'.$tb_transporte_idTransp.'"';?>,"dataini":$('#dataInicio').val(),
				"datafim":$('#dataFim').val(),
				"palavraChave":$('#palavraChave').val(), "pagina":pagina}
			});
			request.done(function(data) {
				//alert('teste');
			    //$("#tabela").html(data);
			    //$('#loading').fadeOut('fast');
				for($i=0; $i < data.length; $i++){
					$("#tabela").html(data[$i]);	
				}
				
			});

			request.fail(function(jqXHR, textStatus) {
				alert( "Erro (Ajax - listar transporte): " + textStatus );
			});
		};
		function fncAceitarLance(){
			//alert($('#idLan').val());
			var idLan = $('#idLan').val(); 
			//alert(idLan);
			window.location.href = "?controle=Lance&acao=aceitarLance&idLan=" + idLan;
		}
		
	function fncCadastrarMensagem(idLan)
		{
			//alert($('#addComment' + idLan).val());
			if ($('#addComment' + idLan).val() <= 0)
			{
				msg4('lanceZero', 'Você não pode enviar uma mesagem em branco.');
			}
			else
			{
				
				msg4('cadastro', 'Cadastrando....');
				$('#submitComment' + idLan).attr('disabled', 'disabled');	
				$('#fconteudoMen').val($('#addComment' + idLan).val());
				$('#fidLan').val(idLan);
				 $.ajax({
                    type: "POST",
                    url: "./?controle=Mensagem&acao=manterMensagem",
                    data: {"fconteudoMen": $('#fconteudoMen').val(),"fidLan": $('#fidLan').val(), "fidPes": $('#fidPes').val()},
                    success: function(html){
                      $('#submitComment' + idLan).removeAttr('disabled');
                      $('#addComment' + idLan).val('');
                      msg4('sucesso', 'Mensagem cadastrada com sucesso.');
                      fncJsonMensagem(idLan);
                    }  
                });
			}
		}
		
		
			
	    </script>
        <style>
            body { padding-top: 120px; }
        </style>
    </head>
    <?php require 'template/header.php'; ?>

    <body id="page-top">
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul class="breadcrumb">
              <li>
                <a href="?controle=Index&acao=Index">Home</a>
              </li>
              <li>
              	<?php
              	if ($_SESSION['codigoPer'] == 'U' )
				{
				?>
                <a href="?controle=Pessoa&acao=areaCliente">Área do Cliente</a> 
                <?php
                }
				?>
				<?php
				if ($_SESSION['codigoPer'] == 'T' )
				{
				?>
                <a href="?controle=Pessoa&acao=areaTransportador">Área do Transportador</a> 
                 <?php
                }
				?>
              </li>
				<li>
					Mensagens
				</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
      
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="text-center">Mensagens</h1>
                    </div>
                </div>
                  <div class="row">
            <div class="col-md-6">
            <script src="http://cdn.jsdelivr.net/webshim/1.12.4/extras/modernizr-custom.js"></script>
			<!-- polyfiller file to detect and load polyfills -->
			<script src="http://cdn.jsdelivr.net/webshim/1.12.4/polyfiller.js"></script>
			<script>
			  webshims.setOptions('waitReady', false);
			  webshims.setOptions('forms-ext', {types: 'date'});
			  webshims.polyfill('forms forms-ext');
			</script>
		<label class="control-label" for="lblDataRetirada">Período da data de recebimento</label><br>                
                                <div class="row">
                                    <div class="col-xs-12 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <div class="input-group date ">
                                                <input type="text" class="form-control" id='dataInicio' name='dataInicio' 
                                                data-validation-required-message="Por favor selecione uma data da coleta do transporte" value="<?php echo  isset($_SESSION['dataini']) ? $_SESSION['dataini'] : ''; ?>"
                                                placeholder="Data Inicial" readonly="" required="" tabindex="3"><span class="input-group-addon">
                                                <i class="glyphicon glyphicon-th"></i></span>
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                    </div>

                                     <div class="col-xs-12 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <div class="input-group date ">
                                                <input type="text" class="form-control" id='dataFim' name='dataFim' 
                                                data-validation-required-message="Por favor selecione uma data da coleta do transporte" value="<?php echo  isset($_SESSION['datafim']) ? $_SESSION['datafim'] : ''; ?>"
                                                placeholder="Data Final" readonly="" required="" tabindex="3"><span class="input-group-addon">
                                                <i class="glyphicon glyphicon-th"></i></span>
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
            <div class="form-group" draggable="true">
              <label class="control-label" for="exampleInputPassword1">Transportador</label>
              <input class="form-control" id="palavraChave" type="text" placeholder="">
            </div>
            
			<div id="centro"></div>
            	<div class="form-group" draggable="true">
		  		<a class="btn btn-primary" id="btnPesquisar">Pesquisar</a>
		  		<a class="btn btn-danger" id="btnLimpar">Limpar</a>
			</div>
			
          </div>
        </div>
            </div>
        </div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12" id="tabela">
		 			</div>
		 			
                </div>
            </div>
        </div>
 			<form action="./?controle=Mensagem&acao=manterMensagem" id="formMensagem" name="formMensagem" method="post">
				<input type="hidden" id="fidPes" name="fidPes" value="<?php echo $idPes ?>">
				<input type="hidden" id="fidLan" name="fidLan" value="">
				<input type="hidden" id="fconteudoMen" name="fconteudoMen" value="">
	 		</form>
			         	

        							<br>
			                        <br>
			                        <div class='text-center'>
                                       <?php
									   if($_SESSION['codigoPer'] == 'A')
									   {
									   ?>
							      	  <a href="?controle=Pessoa&acao=areaAdministrador" type="button" class="btn btn-danger" >Voltar</a>
							      	  <?php
									   }
									   ?>
									   	<?php
									   if($_SESSION['codigoPer'] == 'T')
									   {
									   ?>
							      	  <a href="?controle=Pessoa&acao=areaTransportador" type="button" class="btn btn-danger">Voltar</a>
							      	  <?php
									   }
									   ?>
									      	<?php
									   if($_SESSION['codigoPer'] == 'U')
									   {
									   ?>
							      	  <a href="?controle=Pessoa&acao=areaCliente" type="button" class="btn btn-danger">Voltar</a>
							      	  <?php
									   }
									   ?>
									   </div>
			                        <br>
			                        <br>
			                        
			 <!-- Modal -->
				<div id="addBookDialog" class="modal fade" role="dialog">
				  <div class="modal-dialog">
				
				    <!-- Modal content-->
				    <div class="modal-content">
				      <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal">&times;</button>
				        <h4 class="modal-title"></h4>
				      </div>
				      <div class="modal-body text-center">
				        <p>Tem certeza que deseja aceitar esse Lance?</p>
				        <div class="form-group">
					  		<input type='hidden' id="idLan" name='idLan' value=''>
							<a class="btn btn-primary" id="btnSim"  data-dismiss="modal" onclick=fncAceitarLance();>Sim</a>
							<button type="button" class="btn btn-danger" data-dismiss="modal">Não</button>
					  	</div>
				      </div>
				      <div class="modal-footer">
				      </div>
				    </div>
				
				  </div>
				</div>
				
			<script>
			function msg4(alerta, texto) {
			     var resposta = '';
			     $("#resposta").empty();
			     if (alerta === 'sucesso') {
			       resposta = "<div class='alert btn-success text-center' role='alert'>" +
			         "<a href='#' class='close' data-dismiss='alert' aria-label='Close'>&times;</a>" +
			         texto + "</div>";
			     } else if (alerta === 'lanceZero') {
			       resposta = "<div class='alert btn-warning text-center' role='alert'>" +
			         "<a href='#' class='close' data-dismiss='alert' aria-label='Close'>&times;</a>" +
			         texto + "</div>";
			     } else if (alerta === 'cadastro') {
			       resposta = "<div class='alert btn-primary text-center' role='alert'>" +
			         "<a href='#' class='close' data-dismiss='alert' aria-label='Close'>&times;</a>" +
			         texto + "</div>";
			     }
			     $("#resposta").append(resposta);
			
			     $(".alert").click(function() {
			       $(".alert").hide();
			     });
			   }	
			</script>  
				 
			             
			<script>
			    	$(document).on("click", ".open-AddBookDialog", function () {
						//alert(idLan);
						var idLan = $(this).data('id');
						//alert(idLan);
						$(".modal-body #idLan").val( idLan );
					});                   
			</script>
			<script>
          $('.input-group.date').datepicker({
                    format: "dd-mm-yyyy",
                    todayBtn: "linked",
                    autoclose: true,
                    todayHighlight: true,
                    language: "pt-BR",
                    showButtonPanel: true,
                closeText: 'Clear'
                    });
                    
           </script>
		</body>
    <?php require 'template/footer.php'; ?>
</html>