<?php
$v_params = $this->getParams();
$v_dados = $v_params['v_dados'];
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>
			Dado Adicional
		</title>
		<link rel="stylesheet" type="text/css" href="template/css/default.css" />
	</head>
<body>
	<div align="center">
		<table class='table_list' width="80%">
			<tr>
				<th>
					ID
				</th>
				<th>
					Comentario
				</th>
				<th>
					Preço Maximo
				</th>
							<th>
					Numero de Ajudantes
				</th>
				<th>
					Transporte
				</th>
				<th colspan="3">
					A&ccedil;&otilde;es
				</th>
			</tr>
			<?php
			foreach($v_dados AS $o_dado)
			{
				?>
				<tr>
					<td>
						<?php echo $o_dado->getIdDadAdi()?>
					</td>
					<td>
						<?php echo $o_dado->getComentarioDadAdi()?>
					</td>
					<td>
						<?php echo $o_dado->getPrecoMaximoDadAdi()?>
					</td>
							<td>
						<?php echo $o_dado->getNumAjudantesDadAdi()?>
					</td>
					<td>
						<?php echo $o_dado->getTb_transporte_idTransp()?>
					</td>
					<td align="center">
						<a href='?controle=DadoAdicional&acao=manterDadoAdicional&idDadAdi=<?php echo $o_cado->getIdDadAdi()?>' class='bt_blue'>Editar</a>
					</td>
					<td align="center">
						<a href='?controle=DadoAdicional&acao=apagarDadoAdicional&idDadAdi=<?php echo $o_dado->getIdDadAdi()?>' class='bt_red'>Apagar</a>
					</td>
				</tr>
				<?php
			}
			?>
		</table>
		<br />
		<a href='?controle=DadoAdicional&acao=manterDadoAdicional' class='bt_green'>Novo</a>
	</div>
</body>
</html>