<?php
$v_params = $this->getParams();
$v_lances = $v_params['v_lances'];
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>
			Lance
		</title>
		<link rel="stylesheet" type="text/css" href="template/css/default.css" />
	</head>
<body>
	<div align="center">
		<table class='table_list' width="80%">
			<tr>
				<th>
					ID
				</th>
				<th>
					Valor
				</th>
				<th>
					Data
				</th>
				<th>
					Transporte
				</th>
				<th>
					Transportador
				</th>
				<th colspan="3">
					A&ccedil;&otilde;es
				</th>
			</tr>
			<?php
			foreach($v_lances AS $o_lance)
			{
				?>
				<tr>
					<td>
						<?php echo $o_lance->getIdLan()?>
					</td>
					<td>
						<?php echo $o_lance->getValorLan()?>
					</td>
					<td>
						<?php echo $o_lance->getDataLan()?>
					</td>
						<td>
						<?php echo $o_lance->getTb_transporte_idTransp()?>
					</td>
					<td>
						<?php echo $o_lance->getTb_transportador_idTran()?>
					</td>
					<td align="center">
						<a href='?controle=Lance&acao=manterLance&idLan=<?php echo $o_lance->getIdLan()?>' class='bt_blue'>Editar</a>
					</td>
					<td align="center">
						<a href='?controle=Lanceo&acao=apagarLance&idLan=<?php echo $o_lance->getIdLan()?>' class='bt_red'>Apagar</a>
					</td>
				</tr>
				<?php
			}
			?>
		</table>
		<br />
		<a href='?controle=Lance&acao=manterLance' class='bt_green'>Novo</a>
	</div>
</body>
</html>