<?php
// A sessão precisa ser iniciada em cada página diferente
if (!isset($_SESSION)) session_start();


// Verifica se não há a variável da sessão que identifica o usuário
if ($_SESSION['codigoPer'] <> 'A') {
	// Destrói a sessão por segurança
	session_destroy();
	// Redireciona o visitante de volta pro login
	header("Location: index.php"); exit;
}
$v_params = $this->getParams();
$o_pessoa = $v_params['o_pessoa'];
$v_enderecos = $v_params['v_enderecos'];
?>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="template/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="template/js/fileinput.min.js" type="text/javascript"></script>
        <script src="template/js/fileinput_locale_pt-BR.js" type="text/javascript"></script>
    </head>
    <?php require 'template/header.php'; ?>

    <body id="page-top">
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="text-center">Endereço do Transportador</h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-bordered table-condensed table-hover table-striped">
                            <thead>
                            <tr>
								<th colspan='3'>
									Transportador
								</th>
							</tr>
                                <tr>
                                    <th>Codigo</th>
                                    <th>Foto</th>
                                    <th>Primeiro Nome</th>
                                    <th>Sobrenome</th>
                                    <th>E-mail</th>
                                    <th>CNPJ/CPF</th>
                                    <th>Data Cadastro</th>
                                    <th>Telefone Fixo</th>
                                    <th>Telefone Celular</th>
                                    <th>Perfil</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <?php echo $o_pessoa->getIdPes()?></td>
                                    <td>
                                        <?php echo $o_pessoa->getFotoPes()?> </td>
                                    <td>
                                        <?php echo $o_pessoa->getPrimeiroNomePes()?></td>
                                    <td>
                                        <?php echo $o_pessoa->getSobreNomePes()?></td>
                                    <td>
                                        <?php echo $o_pessoa->getEmailPes()?></td>
                                    <td>
                                        <?php echo $o_pessoa->getCpfCnpjPes()?></td>
                                    <td>
                                        <?php echo $o_pessoa->getDataCadastroPes()?></td>
                                    <td>
                                        <?php echo $o_pessoa->getTelefoneFixoPes()?></td>
                                    <td>
                                        <?php echo $o_pessoa->getTelefoneCelularPes()?></td>
                                    <td>
                                        <?php echo $o_pessoa->getNomePer()?></td>
                                    <td>
                                        <?php echo $o_pessoa->getNomeSta()?></td>               
                                </tr>
                            </tbody>
                        </table>
                        <br>
                        <table class="table table-bordered table-condensed table-hover table-striped">
                            <thead>
                            <tr>
								<th colspan='3'>
									Endereço
								</th>
							</tr>
                                <tr>
                                    <th>Rua</th>
                                    <th>Número</th>
                                    <th>CEP</th>
                                    <th>Complemento</th>
                                    <th>Bairro</th>
                                    <th>Cidade</th>
                                    <th>Estado</th>
                                    <th class="text-center" colspan="3">Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <?php echo $v_enderecos->getRuaEnd()?></td>
                                    <td>
                                        <?php echo $v_enderecos->getNumeroEnd()?> </td>
                                    <td>
                                        <?php echo $v_enderecos->getCepEnd()?></td>
                                    <td>
                                        <?php echo $v_enderecos->getComplementoEnd()?></td>
                                    <td>
                                        <?php echo $v_enderecos->getBairroEnd()?></td>
                                    <td>
                                        <?php echo $v_enderecos->getNomeCid()?></td>
                                    <td>
                                        <?php echo $v_enderecos->getNomeEst()?></td>
                                    <td align="center">
										<a href='?controle=Endereco&acao=manterEndereco&idEnd=<?php echo $v_enderecos->getIdEnd()?>&idPes=<?php echo $o_pessoa->getIdPes()?>' class='btn btn-primary btn-lg'>Editar</a>
									</td> 
                                   
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
     </body>
    <?php require 'template/footer.php'; ?>
</html>