<?php
header('Content-Type: text/html; charset=utf-8');
$v_params = $this->getParams();
$v_transportes = $v_params['v_transportes'];
$opcao = isset($_GET['opcao']) ? $_GET['opcao'] : '';
?>
<html>
	<head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap Core CSS - Uses
        Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
        <link href="template/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="template/css/freelancer.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="template/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
        queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file://
        -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
		<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <link href="template/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="template/js/fileinput.min.js" type="text/javascript"></script>
        <script src="template/js/fileinput_locale_pt-BR.js" type="text/javascript"></script>
        <script type="text/javascript" src="template/js/ajaxupload.3.5.js" ></script>
		<link rel="stylesheet" type="text/css" href="template/css/upload.css" />
	  	<script language="javascript" src="calendar/calendar.js"></script>
	  	<script src="template/js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="template/js/jquery.mask.min.js"></script>
        <link href="template/bootstrap-datepicker/css/bootstrap-datepicker3.css" rel="stylesheet">
		<script src="template/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="template/bootstrap-datepicker/locales/bootstrap-datepicker.pt-BR.min.js"></script>
        <script src="template/js/valorjquery.maskMoney.js" type="text/javascript"></script>
        <script src="template/js/jquery.maskMoney.js" type="text/javascript"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>


	<script>
		function fncSelecionarEstadoOrigem(estado) {
			 $('#cidadeOrigem').load('views/listarCidade.php?estado='+estado.value);
		};
		
		function fncSelecionarEstadoDestino(estado) {
			 $('#cidadeDestino').load('views/listarCidade.php?estado='+estado.value);
		};
		
		$(document).ready(function() {
			$('#btnPesquisar').click(function(){
				//alert('teste');
				fncJson();
			});
		});
		
		function fncJson() {
			//alert($('#cidadeOrigem option:selected').val());	
			var request = $.ajax({
				url: "./views/listarTransporteAtivo.phtml",
				type: "POST",			
				dataType: "json",
				}
			});
			request.done(function(data) {
				//alert('teste');
				//$("#tblItens tbody").html(data);
				for($i=0; $i < data.length; $i++){
					$("#tblItens tbody").html(data[$i]);
				}
			});

			request.fail(function(jqXHR, textStatus) {
				alert( "Erro (Ajax - listar transporte): " + textStatus );
			});
		};
		
		function fncMudarStatus(statusTransp, idTransp, linha) {
			var request = $.ajax({
				url: "./views/alterarTransporte.php",
				type: "POST",			
				dataType: "json",
				data: {"statusTransp":statusTransp, "idTransp":idTransp}
			});
			request.done(function(data) {
				//alert('Status alterado');
				var par = $(linha).parent().parent(); //tr
				//alert(par.html());
				par.remove(); 
			});

			request.fail(function(jqXHR, textStatus) {
				alert( "Erro (Ajax - listar transporte): " + textStatus );
			});
		};
			
		function fncCadastrarLance(idTransp, idPes, linha)
		{
			var par = $(linha).parent().parent(); //tr
			var lance = par.find('input[name="valorLan"]').val();
			if (Number(lance) <= 0)
			{
				alert('Lance deve ser maior que zero');
			}
			else
			{
				alert('teste' + idTransp + ' - ' + idPes + ' - ' +par.find('input[name="valorLan"]').val());
				$('#fValorLan').val(String(lance));
				$('#fTb_transporte_idTransp').val(idTransp);
				$('#fTb_pessoa_idPes').val(idPes);
				alert($('#fValorLan').val() + ' - ' + $('#fTb_transporte_idTransp').val() + ' - ' + $('#fTb_pessoa_idPes').val());
				$( "#formLance" ).submit();
				return false;
			}
		}
		$(function() {
			$("#formLance").on("submit", function(e) {
				e.preventDefault();
				$.ajax({
					url: $(this).attr("action"),
					type: 'POST',
					data: $(this).serialize(),
					success: function(data) {
						alert('teste form');
						fncJson(); // tem que montar um método para remontar só a linha e não chamar tudo de volta
					}
				});
			});
		});
		 $(document).ready(function() {
                        $('#tblItens').DataTable();
                    } );
	</script>
      <style>
            body { padding-top: 210px; }
        </style>
    </head>
    <?php require 'template/header.php'; ?>

<body>
	<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul class="breadcrumb">
              <li>
                <a href="?controle=Index&acao=Index">Home</a>
              </li>
              <li>
              	<?php
              	if ($_SESSION['codigoPer'] == 'U' )
				{
				?>
                <a href="?controle=Pessoa&acao=areaCliente">Área do Cliente</a> 
                <?php
                }
				?>
				<?php
				if ($_SESSION['codigoPer'] == 'T' )
				{
				?>
                <a href="?controle=Pessoa&acao=areaTransportador">Área do Transportador</a> 
                 <?php
                }
				?>
              </li>
               <li class="active">
               <?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "clienteativos")
				{
				?>
				Transportes Ativos
				<?php 
				}
				?>
			
				<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "clienteinativos")
				{
				?>
				Transportes Cancelados
				<?php 
				}
				?>
					<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "transpganhos")
				{
				?>
				Transportes Ganhos
				<?php 
				}
				?>
				<?php 
				if(!isset($_GET['opcao'] )){
					?>
               Pesquisar Transporte
               <?php
				}
				?>
				<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "transpandamento")
				{
				?>
				Transportes em Andamento
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "transpconcluido")
				{
				?>
				Transportes Concluidos
				<?php 
				}
				?>
				</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
	 <div class="section">
      <div class="container">
      	   		 <div class="row">
                    <div class="col-md-12">
                        <h1 class="text-center"> 
                <?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "clienteativos")
				{
				?>
				Lista de Transportes Ativos
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "clienteinativos")
				{
				?>
				Lista de Transportes Cancelados
				<?php 
				}
				?>
				<?php 
				if(!isset($_GET['opcao'] )){
					?>
               Pesquisar Transporte
               <?php
				}
				?>
				<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "transpganhos")
				{
				?>
				Transportes Ganhos
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "transpandamento")
				{
				?>
				Transportes em Andamento
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao']) and $_GET['opcao'] == "transpconcluido")
				{
				?>
				Transportes Concluidos
				<?php 
				}
				?>
				 </h1>
                    </div>
                </div>
        <div class="row">
            <div class="col-md-6">
            <div class="form-group">
              <label class="control-label" for="exampleInputEmail1">Categoria</label>
				<select class="form-control" name='tb_categoria_idCat' id='tb_categoria_idCat'>
				<option value="0">Categoria</option>
				<?php
					$o_categoria = new CategoriaModel();
					$v_categorias = $o_categoria->_list();
					foreach($v_categorias AS $o_categoria)
					{
					?>
						<option value="<?php echo $o_categoria->getIdCat()?>"><?php echo $o_categoria->getNomeCat()?></option>
				<?php
					}
					?>
				</select>
            </div>

			    <script>
			      $(document).ready(function () {
			        $('#dataInicio').datepicker({
			            format: "dd/mm/yyyy",
			            language: "pt-BR"
			        });
			      });
			      $(document).ready(function () {
			        $('#dataFim').datepicker({
			            format: "dd/mm/yyyy",
			            language: "pt-BR"
			        });
			      });
			    </script>
			<label class="control-label" for="lblDataRetirada">Período da data de retirada</label><br>               
                                <div class="row">
                                    <div class="col-xs-12 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <div class="input-group date ">
                                                <input type="text" class="form-control" id='dataInicio' name='dataInicio' 
                                                data-validation-required-message="Por favor selecione uma data da coleta do transporte" value="<?php echo  isset($_SESSION['dataini']) ? $_SESSION['dataini'] : ''; ?>"
                                                placeholder="Data Inicial" readonly="" required="" tabindex="3"><span class="input-group-addon">
                                                <i class="glyphicon glyphicon-th"></i></span>
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                    </div>

                                     <div class="col-xs-12 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <div class="input-group date ">
                                                <input type="text" class="form-control" id='dataFim' name='dataFim' 
                                                data-validation-required-message="Por favor selecione uma data da coleta do transporte" value="<?php echo  isset($_SESSION['datafim']) ? $_SESSION['datafim'] : ''; ?>"
                                                placeholder="Data Final" readonly="" required="" tabindex="3"><span class="input-group-addon">
                                                <i class="glyphicon glyphicon-th"></i></span>
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
           <div class="form-group">
              <label class="control-label" for="exampleInputPassword1">Estado origem</label>
				<select class="form-control" name='estadoOrigem' id='estadoOrigem' onChange="fncSelecionarEstadoOrigem(this)">
				<option value="0">Estado Origem</option>
				<?php
					$o_estado = new EstadoModel();
					$v_estados = $o_estado->_list();
					foreach($v_estados AS $o_estado)
					{
					?>
						<option value="<?php echo $o_estado->getIdEst()?>"><?php echo $o_estado->getUfEst()?></option>
				<?php
					}
					?>
				</select>
            </div>
            <div class="form-group" draggable="true">
              <label class="control-label" for="exampleInputEmail1">Cidade origem</label>
					<select class="form-control" name='cidadeOrigem' id='cidadeOrigem'>
					<option value="0">Cidade Origem</option>
				</select>
            </div>
            </div>
          <div class="col-md-6">
             <div class="form-group">
              <label class="control-label" for="exampleInputPassword1">Estado destino</label>
				<select class="form-control" name='estadoDestino' id='estadoDestino' onChange="fncSelecionarEstadoDestino(this)">
				<option value="0">Estado Destino</option>
				<?php
					$o_estado = new EstadoModel();
					$v_estados = $o_estado->_list();
					foreach($v_estados AS $o_estado)
					{
					?>
						<option value="<?php echo $o_estado->getIdEst()?>"><?php echo $o_estado->getUfEst()?></option>
				<?php
					}
					?>
				</select>
            </div>
            
            <div class="form-group" draggable="true">
              <label class="control-label" for="exampleInputEmail1">Cidade destino</label>
				<select class="form-control" name='cidadeDestino' id='cidadeDestino'>
					<option value="0">Cidade Destino</option>
				</select>
            </div>
			
            <div class="form-group" draggable="true">
              <label class="control-label" for="exampleInputPassword1">Palavra-chave</label>
              <input class="form-control" id="palavraChave" placeholder="">
            </div>
			
            <div class="form-group" draggable="true">
		  		<a class="btn btn-primary" id="btnPesquisar">Pesquisar</a>
			</div>
          </div>
        </div>
      </div>
    </div>
   </div>
  	<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
			<table class="table table-bordered table-condensed table-hover table-striped" id="tblItens" width="100%">
				<thead>
					<tr>
						<th style="text-align:center;" width="20px">Detalhes<br>do Transporte</th>
						<th style="text-align:center;" width="80px">Data<br>Pedido</th>
						<th style="text-align:center;" width="90px">Foto</th>
						<th style="text-align:center;" width="200px">Descrição</th>
						<th style="text-align:center;" width="200px">Endereço<br>de Origem</th>
						<th style="text-align:center;" width="200px">Endereço<br>de Destino</th>
						<th style="text-align:center;" width="50px">Data<br>Transporte</th>
						<th style="text-align:center;" width="50px">Qtde.<br>Lances</th>
						<th style="text-align:center;" width="80px">Menor<br>Lance</th>
						<?php if ($opcao == 'transpconcluido') { ?>
							<th class="text-center" colspan="1">Ações</th>
						<?php } elseif ($opcao == 'transpandamento') { ?>
							<th class="text-center" colspan="2">Ações</th>
						<?php } elseif ($opcao == 'clienteativos') { ?>
							<th class="text-center" colspan="3">Ações</th>
						<?php } elseif ($opcao == 'clienteinativos') { ?>
							<th class="text-center" colspan="2">Ações</th>
						<?php } elseif ($opcao == 'transpganhos') { ?>
							<th class="text-center" colspan="1">Ações</th>
						<?php } else{ ?>
							<th style="text-align:center;" colspan="2" width="100px">Novo lance</th>
							 
						<?php } ?>
					</tr>
				</thead>
				<tbody>
					<?php 
                                	foreach($v_transportes AS $o_transporte){
                                 ?>
                                <tr>
                                    	<td style="text-align:center;"><a class="btn btn-primary btn-xs" href="?controle=Transporte&acao=manterTransporte&idTransp=<?php echo $o_transporte->getIdTransp() ?>&consulta=S">Detalhes</a></td>
										<td style="text-align:center;"><?php echo date('d/m/Y', strtotime($o_transporte->getDataCadastroTransp())) ?></td>
										<td style="text-align:center;"><img style="width:80px;" src="$str_img"></td>
										<td><?php echo $o_transporte->getDescricaoTransp() ?></td>
										<td><?php echo $o_transporte->getRuaOrigemEndTran().' - '.$o_transporte->getBairroOrigemEndTran().' - '.$o_transporte->getCidOrigem().'/'.$o_transporte->getEstOrigem() ?></td>
										<td><?php echo $o_transporte->getRuaDestinoEndTran().' - '.$o_transporte->getBairroDestinoEndTran().' - '.$o_transporte->getCidDestino().'/'.$o_transporte->getEstDestino() ?></td>
										<td style="text-align:center;"><?php echo date('d/m/Y', strtotime($o_transporte->getDataRetiradaTransp())) ?></td>
										<td style="text-align:center;"><?php echo $o_transporte->getQtdeLan() ?></td>
										<td style="text-align:right;"><?php echo number_format($o_transporte->getMenorLan(), 2, ',', '.') ?></td>
									<?php								
									if ($opcao == 'clienteativos') 
									{
									?>
										<td style="text-align:center;"><a class="btn btn-danger btn-xs"  onclick=fncMudarStatus("X",'.$o_transporte->idTransp.',this);>Cancelar</a></td> <!-- alterar o status do transporte para X -->
										<td style="text-align:center;"><a class="btn btn-success btn-xs" href="?controle=Lance&acao=ListarLance&tb_transporte_idTransp=$o_transporte->idTransp&opcao=clienteativos" class="btn btn-success btn-xs">Ver Lances</a></td>
										<td style="text-align:center;"><a class="btn btn-primary btn-xs" href="?controle=Transporte&acao=manterTransporte&idTransp=$o_transporte->idTransp">Editar</a></td>								
									<?php
									}
									elseif ($opcao == 'clienteinativos') {
									?>
										<td style="text-align:center;"><a class="btn btn-primary btn-xs" onclick=fncMudarStatus("A",'.$o_transporte->idTransp.',this);>Ativar</a></td> <!-- alterar o status do transporte para A -->
										<td style="text-align:center;"><a class="btn btn-success btn-xs" href="?controle=Lance&acao=ListarLance&tb_transporte_idTransp=$o_transporte->idTransp&opcao=clienteinativos">Ver Lances</a></td>
									<?php
									}
									elseif ($opcao == 'transpandamento') {
									?>
										<td style="text-align:center;"><a class="btn btn-danger btn-xs" onclick=fncMudarStatus("X",'.$o_transporte->idTransp.',this);>Cancelar</a></td> <!-- alterar o status do transporte para x -->
										<td style="text-align:center;"><a class="btn btn-info btn-xs" onclick=fncMudarStatus("C",'.$o_transporte->idTransp.',this);>Concluir</a></td> <!-- alterar o status do transporte para C -->
									<?php
									}	
									elseif ($opcao == 'transpconcluido') {
									?>
										<td style="text-align:center;"><a class="btn btn-warning btn-xs" href="?controle=Lance&acao=ListarLance&tb_transporte_idTransp=$o_transporte->idTransp">Avaliar Transporte</a></td>
										
									<?php
									}
									elseif ($opcao == 'transpganhos') {
									?>
										<td>$o_transporte->nomeStaTransp</td>
									<?php
									}
									else{
									?>
							
										<td style="text-align:center;"><input type="text" name="valorLan" max="999999" min="1" style="width:70px;"></td>
										<td style="text-align:center;"><a class="btn btn-success btn-xs" onclick=fncCadastrarLance('.<?php echo $o_transporte->getIdTransp() ?>.','.<?php echo$_SESSION['idPes'] ?>.',this); >Cadastrar Lance</a></td>
										<script type="text/javascript">$("#valorLan").maskMoney();</script>
                                    <?php 
                                		} 
                                    ?>
         						</tr>
         						<?php
         						}
         						?>
				</tbody>
			</table>
			<br /><br />
			</div>
			</div>
      </div>
    </div>
   
			    					<br>
			                        <br>
			                        <div class='text-center'>
                                       <?php
									   if($_SESSION['codigoPer'] == 'A')
									   {
									   ?>
							      	  <a href="?controle=Pessoa&acao=areaAdministrador" type="button" class="btn btn-danger" >Voltar</a>
							      	  <?php
									   }
									   ?>
									   	<?php
									   if($_SESSION['codigoPer'] == 'T')
									   {
									   ?>
							      	  <a href="?controle=Pessoa&acao=areaTransportador" type="button" class="btn btn-danger">Voltar</a>
							      	  <?php
									   }
									   ?>
									      	<?php
									   if($_SESSION['codigoPer'] == 'U')
									   {
									   ?>
							      	  <a href="?controle=Pessoa&acao=areaCliente" type="button" class="btn btn-danger">Voltar</a>
							      	  <?php
									   }
									   ?>
									   </div>
			                        <br>
			                        <br>
	</form>
	 <form action="./?controle=Lance&acao=cadastrarLance" id="formLance" method="post">
		<input type="hidden" id="fValorLan" name="fValorLan" value="">
		<input type="hidden" id="fTb_transporte_idTransp" name="fTb_transporte_idTransp" value="">
		<input type="hidden" id="fTb_pessoa_idPes" name="fTb_pessoa_idPes" value="">
	 </form>
	  
</body>
 <?php require 'template/footer.php'; ?>
</html>