<?php
header('Content-Type: text/html; charset=utf-8');
// A sessão precisa ser iniciada em cada página diferente
if (!isset($_SESSION)) session_start();
// Verifica se não há a variável da sessão que identifica o usuário
if ($_SESSION['codigoPer'] <> 'A') {
    // Destrói a sessão por segurança
    session_destroy();
    // Redireciona o visitante de volta pro login
    header("Location: index.php"); exit;
}
$v_params = $this->getParams();
$o_voucher = $v_params['o_voucher'];
?>
<html>  
    <head>
        <!-- Bootstrap Core CSS - Uses
        Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
        <link href="template/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="template/css/freelancer.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="template/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
        queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file://
        -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="template/js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="template/js/jquery.mask.min.js"/></script>
        <script src="template/js/jquery.maskMoney.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="template/AdminLTE.min.css" />
        <link href="template/bootstrap-datepicker/css/bootstrap-datepicker3.css" rel="stylesheet">
		<script src="template/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="template/bootstrap-datepicker/locales/bootstrap-datepicker.pt-BR.min.js"></script>
          <style>
            body { padding-top: 120px; }
        </style>
    </head>
       <?php require 'template/header.php'; ?>

    <body id="page-top">
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul class="breadcrumb">
              <li>
                <a href="controle=Index&acao=Index">Home</a>
              </li>
              <li>
                <a href="?controle=Pessoa&acao=areaAdministrador">Área do Administrador</a> 
              </li>
               <li class="active">
                <a href="?controle=Voucher&acao=listarVoucher">Lista de Vouchers</a> 
              </li>
              <li>
              	<?php if(isset($_GET['idVoucher'])){ ?>
              		Editar Voucher
              		<?php
				}
				else{
				?>
				Novo Voucher
				
				<?php
				}
				?>
				
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="text-center"><?php if(isset($_GET['idVou'])){ ?>
              		Editar Voucher
              		<?php
				}
				else{
				?>
				Novo Voucher
				
				<?php
				}
				?></h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <form role="form" method="post">
                            <div class="form-group">
                                <label class="control-label">Código</label>
                                <input type="text" class="form-control input-lg" placeholder="Código"  maxlength="18"
                                id="codigoVou"  name="codigoVou" required="" tabindex="3" value='<?php echo $o_voucher->getCodigoVou() ?>' 
                                data-validation-required-message="Por favor coloque um código..">
                                <p class="help-block text-danger"></p>
                            </div>
                            
                               <div class="form-group">
                                    <label>Data de Validade</label>
                                    <div class="input-group date ">
                                        <input type="text" class="form-control input-lg" id='dataValidadeVou' name='dataValidadeVou' 
                                        data-validation-required-message="Por favor selecione uma data de validade" value="<?php if($o_voucher->getDataValidadeVou())echo date('d-m-Y', strtotime($o_voucher->getDataValidadeVou()))?>"
                                        placeholder="Data de validade" readonly="" required="" tabindex="3"><span class="input-group-addon">
                                        <i class="glyphicon glyphicon-th"></i></span>
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                            
                            <div class="row">
                                <div class="col-md-12 text-center">
                                    <input type="hidden" name="controle" value="Voucher">
                                    <input type="hidden" name="acao" value="manterVoucher">
                                    <button type="submit" class="btn btn-primary">Confirmar</button> 
                                    <a href="?controle=Voucher&acao=listarVoucher" type="button" class="btn btn-danger">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <script>
              $('.input-group.date').datepicker({
                    format: "dd-mm-yyyy",
                    todayBtn: "linked",
                    autoclose: true,
                    todayHighlight: true,
                    language: "pt-BR",
                    startDate: 'today'
                    });
        </script>
        
        <script>
                    $('form').validate({
            
            highlight: function(element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function(element) {
                $(element).closest('.form-group').removeClass('has-error');
            },
            errorElement: 'span',
            errorClass: 'help-block',
            errorPlacement: function(error, element) {
                if(element.parent('.input-group').length) {
                    error.insertAfter(element.parent());
                } else {
                    error.insertAfter(element);
                }
            }
        });
        </script>
        <br>
        <br>
        <?php require 'template/footer.php'; ?>
    </body>
</html>