<?php
$v_params = $this->getParams();
$o_boleto = $v_params['o_boleto']
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>
			Savicki
		</title>
		<link rel="stylesheet" type="text/css" href="template/css/default.css" />
	</head>
<body>
	<div align="center">
		<form method='post'>
		<table class='table_list' width="300">
			<tr>
				<th>
					Data
				</th>
				<th colspan="2">
					A&ccedil;&otilde;es
				</th>
			</tr>
			<tr>
				<td>
					<input type='text' name='dataBol' value='<?php echo $o_boleto->getDataBol()?>'> 
				</td>
				<td align="center">
					<a href='?controle=Boleto&acao=listarBoleto' class='bt_red'>Cancelar</a>
				</td>
				<td align="center">
					<input type='hidden' name='controle' value='Boleto'>
					<input type='hidden' name='acao' value='manterBoleto'>
					<input type='hidden' name='idBol' value='<?php echo $o_boleto->getIdBol()?>'>
					<button type='submit' class='bt_green'>Salvar</button>
				</td>
			</tr>			
		</table>
		</form>
	</div>
	<?php require CST_PATH . '\views\_includes\footer.php'; ?>
</body>
</html>