<?php
$v_params = $this->getParams();
$o_dado = $v_params['o_dado'];
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>
			DadoAdicional
		</title>
		<link rel="stylesheet" type="text/css" href="template/css/default.css" />
	</head>
<body>
	<div align="center">
		<form method='post'>
		<table class='table_list' width="300">
			<tr>
				<th>
					Comentario
				</th>
				<th>
					Preço Maximo
				</th>
							<th>
					Numero de Ajudantes
				</th>
				<th>
					Transporte
				</th>
				<th colspan="2">
					A&ccedil;&otilde;es
				</th>
			</tr>
			<tr>
				<td>
					<input type='text' name='comentarioDadAdi' value='<?php echo $o_dado->getComentarioDadAdi()?>'> 
				</td>
				<td>
					<input type='text' name='precoMaximoDadAdi' value='<?php echo $o_dado->getPrecoMaximoDadAdi()?>'>
				</td>
					<td>
					<input type='text' name='numAjudantesDadAdi' value='<?php echo $o_dado->getNumAjudantesDadAdi()?>'> 
				</td>
				<td>
					<input type='text' name='tb_transporte_idTransp' value='<?php echo $o_dado->getTb_transporte_idTransp()?>'>
				</td>					
				<td align="center">
					<a href='?controle=DadoAdicional&acao=listarDadoAdicional' class='bt_red'>Cancelar</a>
				</td>
				<td align="center">
					<input type='hidden' name='controle' value='DadoAdicional'>
					<input type='hidden' name='acao' value='manterDadoAdicional'>
					<input type='hidden' name='idDadAdi' value='<?php echo $o_dado->getIdDadAdi()?>'>
					<button type='submit' class='bt_green'>Salvar</button>
				</td>
			</tr>			
		</table>
		</form>
	</div>
</body>
</html>