<?php
$v_params = $this -> getParams();
$o_lance = $v_params['o_lance'];
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title> Lance </title>
		<link rel="stylesheet" type="text/css" href="template/css/default.css" />
	</head>
	<body>
		<div align="center">
			<form method='post'>
				<table class='table_list' width="300">
					<tr>
						<th> Valor </th>
						<th> Data </th>
						<th> Transporte </th>
						<th> Transportador </th>
						<th colspan="2"> A&ccedil;&otilde;es </th>
					</tr>
					<tr>
						<td>
						<input type='text' name='valorLan' value='<?php echo $o_lance->getValorLan()?>'>
						</td>
						<td>
						<input type='text' name='dataLan' value='<?php echo $o_lance->getDataLan()?>'>
						</td>
						<td>
						<input type='text' name='tb_transporte_idTransp' value='<?php echo $o_lance->getTb_transporte_idTransp()?>'>
						</td>
						<td>
						<input type='text' name='tb_transportador_idTran' value='<?php echo $o_lance->getTb_transportador_idTran()?>'>
						</td>
						<td align="center"><a href='?controle=Lance&acao=listarLance' class='bt_red'>Cancelar</a></td>
						<td align="center">
						<input type='hidden' name='controle' value='Lance'>
						<input type='hidden' name='acao' value='manterLance'>
						<input type='hidden' name='idLan' value='<?php echo $o_lance->getIdLan()?>'>
						<button type='submit' class='bt_green'>
							Salvar
						</button></td>
					</tr>
				</table>
			</form>
		</div>
	</body>
</html>