<?php
$v_params = $this->getParams();
$o_administrador = $v_params['o_administrador'];
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>
			Administrador
		</title>
		<link rel="stylesheet" type="text/css" href="template/css/default.css" />
	</head>
<body>
	<div align="center">
		<form method='post'>
		<table class='table_list' width="300">
			<tr>
				<th>
					Nome
				</th>
				<th>
					Sobrenome
				</th>
				<th>
					Data Cadastro
				</th>
				<th>
					Status
				</th>
				<th>
					Usuario
				</th>
				<th colspan="2">
					A&ccedil;&otilde;es
				</th>
			</tr>
			<tr>
				<td>
					<input type='text' name='primeiroNomeAdm' value='<?php echo $o_administrador->getPrimeiroNomeAdm()?>'>
				</td>	
					<td>
					<input type='text' name='sobreNomeAdm' value='<?php echo $o_administrador->getSobreNomeAdm()?>'> 
				</td>
				<td>
					<input type='text' name='dataCadastroAdm' value='<?php echo $o_administrador->getDataCadastroAdm()?>'>
				</td>
				<td>
					<input type='text' name='statusAdm' value='<?php echo $o_administrador->getStatusAdm()?>'>
				</td>		
				<td>
					<input type='text' name='tb_usuario_idUsu' value='<?php echo $o_administrador->getTb_usuario_idUsu()?>'> 
				</td>			
				<td align="center">
					<a href='?controle=Administrador&acao=listarAdministrador' class='bt_red'>Cancelar</a>
				</td>
				<td align="center">
					<input type='hidden' name='controle' value='Administrador'>
					<input type='hidden' name='acao' value='manterAdministrador'>
					<input type='hidden' name='idAdm' value='<?php echo $o_administrador->getIdAdm()?>'>
					<button type='submit' class='bt_green'>Salvar</button>
				</td>
			</tr>			
		</table>
		</form>
	</div>
</body>
</html>