  <?php
    header('Content-Type: text/html; charset=utf-8');
  // A sessão precisa ser iniciada em cada página diferente
if (!isset($_SESSION)) session_start();


// Verifica se não há a variável da sessão que identifica o usuário
if ($_SESSION['codigoPer'] <> 'A') {
	// Destrói a sessão por segurança
	session_destroy();
	// Redireciona o visitante de volta pro login
	header("Location: index.php"); exit;
}
  $v_params = $this->getParams();
  $o_mensalidade = $v_params['o_mensalidade'];
  ?>
 <html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap Core CSS - Uses
        Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
        <link href="template/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="template/css/freelancer.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="template/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
        queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file://
        -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <link href="template/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="template/js/fileinput.min.js" type="text/javascript"></script>
        <script src="template/js/fileinput_locale_pt-BR.js" type="text/javascript"></script>
        <script src="template/js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="template/js/jquery.mask.min.js"></script>
        <link rel="stylesheet" type="text/css" href="template/AdminLTE.min.css" />
         <link href="template/bootstrap-datepicker/css/bootstrap-datepicker3.css" rel="stylesheet">
		<script src="template/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="template/bootstrap-datepicker/locales/bootstrap-datepicker.pt-BR.min.js"></script>
	  
	  	<script>
  
		  /*formata input com máscara de moeda
		  Ex. onKeyUp="moeda(this)*/
		  function moeda(z){
			  v = z.value;
			  v=v.replace(/\D/g,"")  //permite digitar apenas números
			  v=v.replace(/[0-9]{12}/,"inválido")   //limita pra máximo 999.999.999,99
			  v=v.replace(/(\d{1})(\d{8})$/,"$1.$2")  //coloca ponto antes dos últimos 8 digitos
			  v=v.replace(/(\d{1})(\d{5})$/,"$1.$2")  //coloca ponto antes dos últimos 5 digitos
			  v=v.replace(/(\d{1})(\d{1,2})$/,"$1,$2")	//coloca virgula antes dos últimos 2 digitos
			  z.value = v;
		  }
		  $(document).ready(function() {
			  $('#pesqFornecedor').click(function(){
				  jQuery('#dialog').load('?controle=Pessoa&acao=pesquisarTransportador&tipo=T').dialog('open'); 
				  return false;
			  });
			  $('#pesqUsuario').click(function(){
				  jQuery('#dialog').load('?controle=Pessoa&acao=pesquisarUsuario&tipo=C').dialog('open'); 
				  return false;
			  });
		  });
	  	</script>
       <style>
            body { padding-top: 120px; }
        </style>
    </head>
    
    <?php require 'template/header.php'; ?>
   <body id="page-top">
   	<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul class="breadcrumb">
              <li>
                <a href="?controle=Index&acao=Index">Home</a>
              </li>
              <li>
                <a href="?controle=Pessoa&acao=areaAdministrador">Área do Administrador</a> 
              </li>
              <li>
              	<a href="?controle=Mensalidade&acao=controlarMensalidade">Controlar Mensalidade</a>
              </li>
               <li class="active">
               		Mensalidade
               </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="text-center">Mensalidade</h1>
                    </div>
                </div>
                <div class="row">
     
	  <div class="row">
                  <div class="col-md-6 col-md-offset-3">
                    <form role="form" method="post">
                     <div class="form-group">
                      	<label class="control-label" for="primeiroNomePes">Transportador</label>
                        <input class="form-control" placeholder="" type="text" readonly="true"
                        name="primeiroNomePes" value='<?php echo $o_mensalidade->getPrimeiroNomePes() . ' ' . $o_mensalidade->getSobreNomePes() ?>'>
                      </div>
                      
                      <div class="form-group">
                      	<label class="control-label" for="dataVencimentoMensa">Data de vencimento</label>
                        <input class="form-control" placeholder="" type="text" readonly="true"
                        name="dataVencimentoMensa" id="dataVencimentoMensa" value='<?php if($o_mensalidade->getDataVencimentoMensa()){
										echo date('d-m-Y', strtotime($o_mensalidade->getDataVencimentoMensa()));
										} else
										echo  ''; ?>'>
                      </div>
                      
                
        			
        	   <div class="input-group">
               	<label class="control-label">Data de Pagamento</label>
               		<div class="form-group col-xs-12  controls">
   							<div class="input-group date">
	            				<input type="text" class="form-control" id='dataPagamentoMensa' name='dataPagamentoMensa' 
								value="<?php if(date('d-m-Y', strtotime($o_mensalidade->getDataPagamentoMensa())) and date('d-m-Y', strtotime($o_mensalidade->getDataPagamentoMensa())) > '01-01-1970') echo date('d-m-Y', strtotime($o_mensalidade->getDataPagamentoMensa())) ?>" 
								data-validation-required-message="Por favor selecione uma data de pagamento"
			                    placeholder="Data de pagamento" readonly="" required=""><span class="input-group-addon">
			                    <i class="glyphicon glyphicon-th"></i></span>
							<p class="help-block text-danger"></p>
        					</div>
        			</div>
        		</div>
        		
        		<br />
        		
        		<script>
        	 	$('.input-group.date').datepicker({
			        format: "dd-mm-yyyy",
			        todayBtn: "linked",
			        autoclose: true,
			        todayHighlight: true,
			        language: "pt-BR",
			        startDate: 'today'
			         });
			    </script>
			   
					
					   <div class="form-group">
						  <label class="control-label" for="lblValor">Valor</label>
							  <input type='text' class="form-control" name='valorMensa' id="valorMensa"
							  value="<?php if($o_mensalidade->getValorMensa()) echo 'R$ ' . number_format($o_mensalidade->getValorMensa(), 2, ',', '.')?>"
							  required data-thousands="." data-decimal="," data-prefix="R$ " 
							  placeholder="Informe o valor do lance"> 
					  </div>
					   <script type="text/javascript">$("#valorMensa").maskMoney();</script>
					   
					  <div class="form-group">
						  <label class="control-label" for="lblSituacao">Situação</label>
							<div class="form-control">
							  <?php
								  $o_situacaomensalidade = new SituacaoMensalidadeModel();
								  $v_situacaomensalidades = $o_situacaomensalidade->_list();
								  foreach($v_situacaomensalidades AS $o_situacaomensalidade)
								  {
							  ?>
								  <input type="radio" name='tb_situacaoMensalidade_idSit' value="<?php echo $o_situacaomensalidade->getIdSit()?>" <?php if ($o_mensalidade->getTb_situacaoMensalidade_idSit() == $o_situacaomensalidade->getIdSit()) echo 'checked'?>><?php echo $o_situacaomensalidade->getDescricaoSit()?>
							  <?php
									}
							  ?>
						</div>
					  </div>
					    <br>
      	  				<br>
					  <div class="form-group">
					  	<div class="col-md-12 text-center">
							  <input type='hidden' name='controle' value='Mensalidade'>
							  <input type='hidden' name='acao' value='manterMensalidade'>
							  <input type='hidden' name='idMensa' value='<?php echo $o_mensalidade->getIdMensa()?>'>
							  <input type='hidden' name='tb_pessoa_idPes' value='<?php echo $o_mensalidade->getTb_pessoa_idPes() ?>'>
							  <button type='submit' class='btn btn-primary'>Salvar</button>
							  <a href='?controle=Mensalidade&acao=controlarMensalidade' class='btn btn-danger'>Cancelar</a>
						</div>
					  </div>
					  </form>
				 </div>
			  </div>
		  </div>
  		</div>
      	  <script>
	      	  	$('form').validate({
		        highlight: function(element) {
		            $(element).closest('.form-group').addClass('has-error');
		        },
		        unhighlight: function(element) {
		            $(element).closest('.form-group').removeClass('has-error');
		        },
		        errorElement: 'span',
		        errorClass: 'help-block',
		        errorPlacement: function(error, element) {
		            if(element.parent('.input-group').length) {
		                error.insertAfter(element.parent());
		            } else {
		                error.insertAfter(element);
		            }
		        }
		    });
      	</script>
      	
      	</body>
  <?php require 'template/footer.php'; ?>
    
  </html>