<?php
// A sessão precisa ser iniciada em cada página diferente
if (!isset($_SESSION)) session_start();


// Verifica se não há a variável da sessão que identifica o usuário
if ($_SESSION['codigoPer'] <> 'T') {
	// Destrói a sessão por segurança
	session_destroy();
	// Redireciona o visitante de volta pro login
	header("Location: index.php"); exit;
}
$v_params = $this->getParams();
$v_lances = $v_params['v_lances'];
?>
<html>   
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap Core CSS - Uses
        Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
        <link href="template/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="template/css/freelancer.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="template/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
        queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file://
        -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link href="template/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="template/js/fileinput.min.js" type="text/javascript"></script>
        <script src="template/js/fileinput_locale_pt-BR.js" type="text/javascript"></script>
        <script type="text/javascript" src="template/js/ajaxupload.3.5.js" ></script>
		<link rel="stylesheet" type="text/css" href="template/css/upload.css" />
	  	<script src="template/js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="template/js/jquery.mask.min.js"></script>
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
         <link rel="stylesheet" type="text/css" href="template/css/datepicker.css">
        <script src="template/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="template/js/locales/bootstrap-datepicker.pt-BR.js"></script>
        <script src="template/js/jquery.maskMoney.js" type="text/javascript"></script>
	    <script src="template/js/star-ratingview.js" type="text/javascript"></script>
		<script>
		
		function fncSelecionarEstadoOrigem(estado) {
			 $('#cidadeOrigem').load('views/listarCidade.php?estado='+estado.value);
		};
		
		function fncSelecionarEstadoDestino(estado) {
			 $('#cidadeDestino').load('views/listarCidade.php?estado='+estado.value);
		};
			$(document).ready(function() {
				$('#btnPesquisar').click(function(){
					//alert('teste');
					fncJson(1);
				});
				     $('#btnLimpar').click(function(){
                //alert('teste');
                $('#dataInicio').val('');
                $('#dataFim').val('');
                $('#tb_categoria_idCat').val(0);
                $('#cidadeOrigem').val(0);
                $('#cidadeDestino').val(0);
                $('#estadoOrigem').val(0);
                $('#estadoDestino').val(0);
                $('#palavraChave').val('');
                $("input:radio").attr("checked", false);
                
                fncJson(1);
            });
			});
			
			$(document).ready(function() {
				fncJson(1);	
			});
			
			function fncJson(pagina) {
				//alert(pagina);	
				var request = $.ajax({
					url: "./views/meusLances.php",
					beforeSend: function(){
			              $('#loading').html("<img src='template/img/loading.gif'/>").fadeIn('fast');
					},
					type: "POST",			
					dataType: "json",
					data: { "dataini":$('#dataInicio').val(),
					"datafim":$('#dataFim').val(), "categoria":$('#tb_categoria_idCat').val(),
					"cidadeOrigem":$('#cidadeOrigem option:selected').val(), "cidadeDestino":$('#cidadeDestino option:selected').val(),
					"estadoOrigem":$('#estadoOrigem option:selected').val(), "estadoDestino":$('#estadoDestino option:selected').val(),
					"palavraChave":$('#palavraChave').val(), "pagina":pagina, "idStaTransp":$('#idStaTransp').val(), "myRadio":$('input[name="myRadio"]:checked', '#myForm').val()}
				});
				request.done(function(data) {
					//alert('teste');
				    //$("#tabela").html(data);
				    //$('#loading').fadeOut('fast');
					for($i=0; $i < data.length; $i++){
						$("#tabela").html(data[$i]);	
					}
					$("#tabela").focus();
					
					//alert($('input[name="myRadio"]:checked', '#myForm').val()); 
				});
	
				request.fail(function(jqXHR, textStatus) {
					alert( "Erro (Ajax - listar transporte): " + textStatus );
				});
			};
			
			function load(){
            waitingDialog.show('Carregando Detalhes...Aguarde');
             }
		</script>
          <style>
            body { padding-top: 120px; }
        </style>
    </head>
    <?php require 'template/header.php'; ?>

    <body id="page-top">
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul class="breadcrumb">
              <li>
                <a href="?controle=Index&acao=Index">Home</a>
              </li>
              <li>
                <a href="?controle=Pessoa&acao=areaTransportador">Área do Transportador</a>
              </li>
              <li class="active">
                Meus Lances
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    
    <div class="section">
      <div class="container">
      	   		 <div class="row">
                    <div class="col-md-12">
                        <h1 class="text-center"> 
                		Meus Lances
				 		</h1>
                    </div>
                </div>
       <div class="row">
            <div class="col-md-6">
            <div class="form-group">
              <label class="control-label" for="exampleInputEmail1">Categoria</label>
                <select class="form-control" name='tb_categoria_idCat' id='tb_categoria_idCat'>
                <option value="0">Categoria</option>
                <?php
                    $o_categoria = new CategoriaModel();
                    $categoria = isset($_SESSION['categoria']) ? $_SESSION['categoria'] : 'null';
                    $v_categorias = $o_categoria->_list();
                    foreach($v_categorias AS $o_categoria)
                    {
                    ?>
                        <option value="<?php echo $o_categoria->getIdCat()?>" <?php if ($o_categoria->getIdCat() ==  $categoria) echo 'selected' ?>><?php echo $o_categoria->getNomeCat()?></option>
                <?php
                    }
                    ?>
                </select>
            </div>
            
            <div class="form-group">
              <label class="control-label" for="exampleInputEmail1">Situação Transporte</label>
                <select class="form-control" name='idStaTransp' id='idStaTransp'>
                <option value="0">Situação Transporte</option>
                <?php
                    $o_situacaoTransp = new StatusTransporteModel();
                    $situacaoTransp = isset($_SESSION['situacaoTransp']) ? $_SESSION['situacaoTransp'] : 'null';
                    $v_situacao = $o_situacaoTransp->_list();
                    foreach($v_situacao AS $o_situacaoTransp)
                    {
                    ?>
                        <option value="<?php echo $o_situacaoTransp->getIdStaTransp() ?>" <?php if ($o_situacaoTransp->getIdStaTransp() ==  $situacaoTransp) echo 'selected' ?>><?php echo utf8_encode($o_situacaoTransp->getNomeStaTransp())?></option>
                <?php
                    }
                    ?>
                </select>
            </div>
            
        <div class="form-group">
            <label class="control-label" for="exampleInputEmail1">Situação Do Lance</label><br>
            <form id="myForm">
                <label >
                    <input type="radio" name="myRadio" value="A" <?php echo isset($_SESSION['quality']) ? ($_SESSION['quality'] == 'A')?'checked':'' : '' ?>/> Aguardando
                </label> 
                <label >
                    <input type="radio" name="myRadio" value="S" <?php echo isset($_SESSION['quality']) ? ($_SESSION['quality'] == 'S')?'checked':'' : '' ?>/> Ganho
                </label> 
                <label >
                    <input type="radio" name="myRadio" value="N" <?php echo isset($_SESSION['quality']) ? ($_SESSION['quality'] == 'N')?'checked':'' : '' ?>/> Perdido
                </label> 
             </form>
         </div>
   
            <script src="http://cdn.jsdelivr.net/webshim/1.12.4/extras/modernizr-custom.js"></script>
            <!-- polyfiller file to detect and load polyfills -->
            <script src="http://cdn.jsdelivr.net/webshim/1.12.4/polyfiller.js"></script>
            <script>
              webshims.setOptions('waitReady', false);
              webshims.setOptions('forms-ext', {types: 'date'});
              webshims.polyfill('forms forms-ext');
            </script>
           <label class="control-label" for="lblDataRetirada">Período da data de retirada</label><br>               
                                <div class="row">
                                    <div class="col-xs-12 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <div class="input-group date ">
                                                <input type="text" class="form-control" id='dataInicio' name='dataInicio' 
                                                data-validation-required-message="Por favor selecione uma data da coleta do transporte" value="<?php echo  isset($_SESSION['dataini']) ? $_SESSION['dataini'] : ''; ?>"
                                                placeholder="Data Inicial" readonly="" required="" tabindex="3"><span class="input-group-addon">
                                                <i class="glyphicon glyphicon-th"></i></span>
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                    </div>

                                     <div class="col-xs-12 col-sm-6 col-md-6">
                                        <div class="form-group">
                                            <div class="input-group date ">
                                                <input type="text" class="form-control" id='dataFim' name='dataFim' 
                                                data-validation-required-message="Por favor selecione uma data da coleta do transporte" value="<?php echo  isset($_SESSION['datafim']) ? $_SESSION['datafim'] : ''; ?>"
                                                placeholder="Data Final" readonly="" required="" tabindex="3"><span class="input-group-addon">
                                                <i class="glyphicon glyphicon-th"></i></span>
                                                <p class="help-block text-danger"></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
   
            
           <div class="form-group">
              <label class="control-label" for="exampleInputPassword1">Estado origem</label>
                <select class="form-control" name='estadoOrigem' id='estadoOrigem' onChange="fncSelecionarEstadoOrigem(this)">
                <option value="0">Estado Origem</option>
                <?php
                    $o_estado = new EstadoModel();
                    $v_estados = $o_estado->_list();
                    $estadoOrigem = isset($_SESSION['estadoOrigem']) ? $_SESSION['estadoOrigem'] : 'null';
                    foreach($v_estados AS $o_estado)
                    {
                    ?>
                        <option value="<?php echo $o_estado->getIdEst()?>" <?php echo $o_estado->getIdEst() == $estadoOrigem ? 'selected' : '' ?>><?php echo $o_estado->getUfEst()?></option>
                <?php
                    }
                    ?>
                </select>
            </div>
            <div class="form-group" draggable="true">
              <label class="control-label" for="exampleInputEmail1">Cidade origem</label>
                    <select class="form-control" name='cidadeOrigem' id='cidadeOrigem'>
                    <option value="0">Cidade Origem</option>
                       <?php
                                   $cidadeOrigem = isset($_SESSION['cidadeOrigem']) ? $_SESSION['cidadeOrigem'] : 'null';
                                if ($cidadeOrigem !== NULL)
                                    $cidadeOrigem = $cidadeOrigem;
                                else
                                    $cidadeOrigem = 0;
                                $o_cidade = new CidadeModel();
                                $v_cidades = $o_cidade->_list($estadoOrigem);
                                foreach($v_cidades AS $o_cidade)
                                {
                                ?>
                                    <option value="<?php echo $o_cidade->getIdCid()?>" <?php echo $o_cidade->getIdCid() == $cidadeOrigem ? 'selected' : '' ?>><?php echo utf8_encode($o_cidade->getNomeCid())?></option>
                            <?php
                                }
                                ?>
                </select>
            </div>
            </div>
          <div class="col-md-6">
             <div class="form-group">
              <label class="control-label" for="exampleInputPassword1">Estado destino</label>
                <select class="form-control" name='estadoDestino' id='estadoDestino' onChange="fncSelecionarEstadoDestino(this)">
                <option value="0">Estado Destino</option>
                <?php
                    $o_estado = new EstadoModel();
                    $v_estados = $o_estado->_list();
                    $estadoDestino = isset($_SESSION['estadoDestino']) ? $_SESSION['estadoDestino'] : 'null';
                    foreach($v_estados AS $o_estado)
                    {
                    ?>
                        <option value="<?php echo $o_estado->getIdEst()?>" <?php echo $o_estado->getIdEst() == $estadoDestino ? 'selected' : '' ?>><?php echo $o_estado->getUfEst()?></option>
                <?php
                    }
                    ?>
                </select>
            </div>
            
            <div class="form-group" draggable="true">
              <label class="control-label" for="exampleInputEmail1">Cidade destino</label>
                <select class="form-control" name='cidadeDestino' id='cidadeDestino'>
                    <option value="0">Cidade Destino</option>
                       <?php
                               $cidadeDestino = isset($_SESSION['cidadeDestino']) ? $_SESSION['cidadeDestino'] : 'null';
                                   
                                if ($cidadeDestino !== NULL)
                                        $cidadeDestino = $cidadeDestino;
                                    else
                                        $cidadeDestino = 0;
                                    $o_cidade = new CidadeModel();
                                    $v_cidades = $o_cidade->_list($estadoDestino);
                                    foreach($v_cidades AS $o_cidade)
                                    {
                                    ?>
                                        <option value="<?php echo $o_cidade->getIdCid()?>" <?php echo $o_cidade->getIdCid() == $cidadeDestino ? 'selected' : '' ?>><?php echo utf8_encode($o_cidade->getNomeCid())?></option>
                                <?php
                                    }
                                    ?>
                </select>
            </div>
            
            <div class="form-group" draggable="true">
              <label class="control-label" for="exampleInputPassword1">Palavra-chave</label>
              <input class="form-control" id="palavraChave" placeholder="" value="<?php echo isset($_SESSION['palavraChave']) ? $_SESSION['palavraChave'] : '' ?>">
            </div>
            <div id="centro"></div>
            <div class="form-group" draggable="true">
                <a class="btn btn-primary" id="btnPesquisar">Pesquisar</a>
                <a class="btn btn-danger" id="btnLimpar">Limpar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12" id="tabela">
          	
			</div>
			</div>

      </div>
    </div>
        <br>
			                        <br>
			                        <div class='text-center'>
                                       <?php
									   if($_SESSION['codigoPer'] == 'A')
									   {
									   ?>
							      	  <a href="?controle=Pessoa&acao=areaAdministrador" type="button" class="btn btn-danger" >Voltar</a>
							      	  <?php
									   }
									   ?>
									   	<?php
									   if($_SESSION['codigoPer'] == 'T')
									   {
									   ?>
							      	  <a href="?controle=Pessoa&acao=areaTransportador" type="button" class="btn btn-danger">Voltar</a>
							      	  <?php
									   }
									   ?>
									      	<?php
									   if($_SESSION['codigoPer'] == 'U')
									   {
									   ?>
							      	  <a href="?controle=Pessoa&acao=areaCliente" type="button" class="btn btn-danger">Voltar</a>
							      	  <?php
									   }
									   ?>
									   </div>
			                        <br>
			                        <br>
			                             <script>
        
        var waitingDialog = waitingDialog || (function ($) {
            'use strict';
        
            // Creating modal dialog's DOM
            var $dialog = $(
                '<div class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true" style="padding-top:15%; overflow-y:visible;">' +
                '<div class="modal-dialog modal-m">' +
                '<div class="modal-content">' +
                    '<div class="modal-header"><h3 style="margin:0;"></h3></div>' +
                    '<div class="modal-body">' +
                        '<div class="progress progress-striped active" style="margin-bottom:0;"><div class="progress-bar" style="width: 100%"></div></div>' +
                    '</div>' +
                '</div></div></div>');
        
            return {
                /**
                 * Opens our dialog
                 * @param message Custom message
                 * @param options Custom options:
                 *                options.dialogSize - bootstrap postfix for dialog size, e.g. "sm", "m";
                 *                options.progressType - bootstrap postfix for progress bar type, e.g. "success", "warning".
                 */
                show: function (message, options) {
                    // Assigning defaults
                    if (typeof options === 'undefined') {
                        options = {};
                    }
                    if (typeof message === 'undefined') {
                        message = 'Loading';
                    }
                    var settings = $.extend({
                        dialogSize: 'm',
                        progressType: '',
                        onHide: null // This callback runs after the dialog was hidden
                    }, options);
        
                    // Configuring dialog
                    $dialog.find('.modal-dialog').attr('class', 'modal-dialog').addClass('modal-' + settings.dialogSize);
                    $dialog.find('.progress-bar').attr('class', 'progress-bar');
                    if (settings.progressType) {
                        $dialog.find('.progress-bar').addClass('progress-bar-' + settings.progressType);
                    }
                    $dialog.find('h3').text(message);
                    // Adding callbacks
                    if (typeof settings.onHide === 'function') {
                        $dialog.off('hidden.bs.modal').on('hidden.bs.modal', function (e) {
                            settings.onHide.call($dialog);
                        });
                    }
                    // Opening dialog
                    $dialog.modal();
                },
                /**
                 * Closes dialog
                 */
                hide: function () {
                    $dialog.modal('hide');
                }
            };
        
        })(jQuery);
        
    </script>
    
       <script>
          $('.input-group.date').datepicker({
                    format: "dd-mm-yyyy",
                    todayBtn: "linked",
                    autoclose: true,
                    todayHighlight: true,
                    language: "pt-BR",
                    showButtonPanel: true
                    
                    });
                    
    </script>
	</body>
    <?php require 'template/footer.php'; ?>

</html>