<?php
     
	$v_params = $this->getParams();
	$o_pessoa = $v_params['o_pessoa'];
	if(!isset($_SESSION)) session_start();
	header('Content-Type: text/html; charset=utf-8');
?>
<html>   
    <head>
       <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap Core CSS - Uses
        Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
        <link href="template/css/bootstrap.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="template/css/freelancer.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="template/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
        queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file://
        -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link href="template/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="template/js/fileinput.min.js" type="text/javascript"></script>
        <script src="template/js/fileinput_locale_pt-BR.js" type="text/javascript"></script>
        <script type="text/javascript" src="template/js/ajaxupload.3.5.js" ></script>
        <link rel="stylesheet" type="text/css" href="template/css/upload.css" />
        <script src="template/js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="template/js/jquery.mask.min.js"></script>
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="template/css/datepicker.css">
        <script src="template/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="template/js/locales/bootstrap-datepicker.pt-BR.js"></script>
        <script src="template/js/jquery.maskMoney.js" type="text/javascript"></script>
	    <link rel="stylesheet" href="template/css/star-ratingview.css" media="all" rel="stylesheet" type="text/css"/>
	
	    <script src="template/js/star-ratingview.js" type="text/javascript"></script>
       <style>
            body { padding-top: 120px; }
        </style>
        <script>
            function load(){
            waitingDialog.show('Aceitando...Aguarde');
        }
        function fncAceitarLance(idLan){
            //alert($('#idLan').val());
            //alert(idLan);
            load();
            window.location.href = "?controle=Lance&acao=aceitarLance&idLan=" + idLan;    }
        </script>
    </head>
    <?php require 'template/header.php'; ?>

<body>
	<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
             <ul class="breadcrumb">
            <li>
                <a href="?controle=Index&acao=Index">Home</a>
             </li>
             <li>
              	<?php
              	if ($_SESSION['codigoPer'] == 'U' )
				{
				?>
                <a href="?controle=Pessoa&acao=areaCliente">Área do Cliente</a> 
                <?php
                }
				?>
				<?php
				if ($_SESSION['codigoPer'] == 'T' )
				{
				?>
                <a href="?controle=Pessoa&acao=areaTransportador">Área do Transportador</a> 
                 <?php
                }
				?>
              </li>
                  <li>
               <?php
               	if(isset($_GET['opcao1']) and $_GET['opcao1'] == "clienteativos")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=clienteativos">Transportes Ativos</a>
				<?php 
				}
				?>
			
				<?php
               	if(isset($_GET['opcao1']) and $_GET['opcao1'] == "clienteinativos")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=clienteinativos">Transportes Cancelados</a>
				<?php 
				}
				?>
					<?php
               	if(isset($_GET['opcao1']) and $_GET['opcao1'] == "transpganhos")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=transpganhos">Transportes Ganhos</a>
				<?php 
				}
				?>
				<?php 
				if(isset($_GET['opcao1'] ) and $_GET['opcao1'] == 'clienteativosTrans'){
					?>
               <a href="?controle=Transporte&acao=listartransporte&opcao=clienteativosTrans">Pesquisar Transporte</a>
               <?php
				}
				?>
				<?php
               	if(isset($_GET['opcao1']) and $_GET['opcao1'] == "transpandamento")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=transpandamento">Transportes em Andamento</a>
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao1']) and $_GET['opcao1'] == "transpAndamentoTrans")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=transpAndamentoTrans">Transportes em Andamento</a>
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao1']) and $_GET['opcao1'] == "transpconcluido")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=transpconcluido">Transportes Concluidos</a>
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao1']) and $_GET['opcao1'] == "transpConcluidoTrans")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=transpConcluidoTrans">Transportes Concluidos</a>
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao1']) and $_GET['opcao1'] == "verLance")
				{
				?>
				<a href="?controle=Lance&acao=ListarLance&tb_transporte_idTransp='.$value->idTransp.'&opcao='.$opcao.'">Lances do Transporte</a>
				<?php 
				}
				?>
			   </li>
               <li>
               <?php
               	if(isset($_GET['opcao2']) and $_GET['opcao2'] == "clienteativos")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=clienteativos">Transportes Ativos</a>
				<?php 
				}
				?>
			
				<?php
               	if(isset($_GET['opcao2']) and $_GET['opcao2'] == "clienteinativos")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=clienteinativos">Transportes Cancelados</a>
				<?php 
				}
				?>
					<?php
               	if(isset($_GET['opcao2']) and $_GET['opcao2'] == "transpganhos")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=transpganhos">Transportes Ganhos</a>
				<?php 
				}
				?>
				<?php 
				if(isset($_GET['opcao2'] ) and $_GET['opcao2'] == 'clienteativosTrans'){
					?>
               <a href="?controle=Transporte&acao=listartransporte&opcao=clienteativosTrans">Pesquisar Transporte</a>
               <?php
				}
				?>
				<?php
               	if(isset($_GET['opcao2']) and $_GET['opcao2'] == "transpandamento")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=transpandamento">Transportes em Andamento</a>
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao2']) and $_GET['opcao2'] == "transpAndamentoTrans")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=transpAndamentoTrans">Transportes em Andamento</a>
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao2']) and $_GET['opcao2'] == "transpconcluido")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=transpconcluido">Transportes Concluidos</a>
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao2']) and $_GET['opcao2'] == "transpConcluidoTrans")
				{
				?>
				<a href="?controle=Transporte&acao=listartransporte&opcao=transpConcluidoTrans">Transportes Concluidos</a>
				<?php 
				}
				?>
				<?php
               	if(isset($_GET['opcao2']) and $_GET['opcao2'] == "verLance")
				{
				?>
				<a href="?controle=Lance&acao=ListarLance&tb_transporte_idTransp=<?php echo $_GET['idTransp'] ?>&opcao=<?php echo $_GET['opcao1'] ?>">Lances do Transporte</a>
				<?php 
				}
				?>
				</li>
               <li class="active">
              	Perfil <?php echo $o_pessoa->getPrimeiroNomePes()." ".$o_pessoa->getSobreNomePes()?>
               </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
        <div class="section">
            <div class="container">
                <div class="row">
                   <div class="col-xs-12">
		      			<div class="text-center">
                    	<?php
				        if($o_pessoa->getFotoPes())
						{ ?>
						<img src="<?php echo $o_pessoa->getFotoPes()?>" class="img-thumbnail" alt="Cinque Terre" width="304" height="236">
						<?php
						}else{
							?>
						 <img src="http://pingendo.github.io/pingendo-bootstrap/assets/user_placeholder.png" class="center-block img-circle img-responsive">	
						<?php  	
						}
						?>
                        <div class="text-center">
                        	
                        <label for="valorAva9">Avaliação</label>
                        <input class="ratingInput" type="text" value="<?php echo $o_pessoa->getMedia() ?>"/>
						<div id="ratingCaption" class="starRatingCaptionHolderLocations">
							</div>
                        </div>
                        	<div id="fb-root" style="margin:10px;"></div>
                    </div>
                    </div>
            </div>
        </div>
        <script>
        	$('.ratingInput').rating(
				{
				min: 0,
				max: 10,
				stars: 5,
				readonly: true,
				showClear: false,
				starCaptions: function(val) {
				if(val == 1) {
					return val + ' Star';
				} else {
					return val + ' Stars';
				}
				},
					starCaptionClasses: function(val) {
					return 'label starRatingCaptionLabelDefault';
				},
					captionElement: "#ratingCaption",
				}
			);
        </script>
        
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <h4 class="text-center">Esse transportador ofereceu um lance de:&nbsp;</h4>
                        <h4 class="text-center">R$ <?php echo  number_format($_GET['valorLance'], 2, ',', '.')?></h4>
                        <br>
                        <div class="text-center">
                            <button type="button" class="btn btn-lg btn-primary" data-toggle="modal" data-target="#addBookDialog">Aceitar Lance</button>
                        </div>
                    </div>
                    
                    <div id="addBookDialog" class="modal fade" role="dialog">
					  <div class="modal-dialog">
					    <!-- Modal content-->
					    <div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal">&times;</button>
					        <h4 class="modal-title"></h4>
					      </div>
					      <div class="modal-body text-center">
					        <p>Tem certeza que deseja aceitar o lance desse transportador?</p>
					            <button type="button"  class="btn  btn-primary" data-dismiss="modal" onclick="fncAceitarLance(<?php echo $_GET['idLan']?>)">Sim</button>
								<button type="button" class="btn btn-danger" data-dismiss="modal">Não</button>
						  	</div>
					      </div>
					      <div class="modal-footer">
					      </div>
					    </div>
					  </div>
					  
                    <div class="col-md-6">
                        <div class="col-xs-12 divider text-center">
                            <div class="col-xs-12 col-sm-6 emphasis">
                                <h2>
                                    <strong><?php echo $o_pessoa->getQtdeTransportes() ?></strong>
                                </h2>
                                <p>
                                    <small>Transportes Efetuados</small>
                                </p>
                            </div>
                            <div class="col-xs-12 col-sm-6 emphasis">
                                <h2>
                                    <strong><?php echo $o_pessoa->getQtdeLances() ?></strong>
                                </h2>
                                <p>
                                    <small>Lances Ofertados</small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <br>
    <div class="container">
		<div class="row">
			<h2 class="text-center">Últimas Avaliações</h2>
		</div>
	</div>
    <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                    	<div class="table-responsive">
                        <table class="table table-bordered table-condensed table-hover table-striped">
                        	<?php
								$o_avaliacao = new AvaliacaoModel();
								$v_avaliacoes = $o_avaliacao->_listAvaliacaoTran($_GET['tb_pessoa_idPes']);
								?>
                            <thead>
                                <tr>
                                    <th style="text-align:center;">Avaliação</th>
                                    <th style="text-align:center;">Descrição do Transporte</th>
                                    <th style="text-align:center;">Cliente</th>
                                    <th style="text-align:center;">Data da Avaliação</th>
                                    <th style="text-align:center;">Comentário</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
                                	foreach($v_avaliacoes AS $o_avaliacao){
                                 ?>
                                <tr>
                                    <td style="text-align:center;">
                                    	<input id="valorAva" name="valorAva" type="number" class="rating" min="0" max="10" step="1" data-size="xs"
		           				         data-symbol="&#xf005;" data-glyphicon="false" data-rating-class="rating-fa" class="required-entry form-required aria-required form-control" 
		           				         readonly="" value="<?php echo $o_avaliacao->getMedia() ?>" data-clearable="remove">
									</td>
									<td>
										<?php echo $o_avaliacao->getDescricaoTransp() ?>
									</td>
									<td style="text-align:center;">
										<?php echo $o_avaliacao->getPrimeiroNomePes() ?>
									</td>
									<td style="text-align:center;">
										<?php echo date('d/m/Y', strtotime($o_avaliacao->getDataAva()))?>
									</td>
									<td>
										<?php echo $o_avaliacao->getConteudoAva() ?>
									</td>
                          
                                    <?php 
                                		} 
                                    ?>
         						</tr>
                            </tbody>
                        </table>
                        </div>
                      
                       
                        <br>
                        <br>
                        <div class='text-center'>
                        <a href="?controle=Pessoa&acao=areaCliente" type="button" class="btn btn-danger">Voltar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
        
        var waitingDialog = waitingDialog || (function ($) {
            'use strict';
        
            // Creating modal dialog's DOM
            var $dialog = $(
                '<div class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true" style="padding-top:15%; overflow-y:visible;">' +
                '<div class="modal-dialog modal-m">' +
                '<div class="modal-content">' +
                    '<div class="modal-header"><h3 style="margin:0;"></h3></div>' +
                    '<div class="modal-body">' +
                        '<div class="progress progress-striped active" style="margin-bottom:0;"><div class="progress-bar" style="width: 100%"></div></div>' +
                    '</div>' +
                '</div></div></div>');
        
            return {
                /**
                 * Opens our dialog
                 * @param message Custom message
                 * @param options Custom options:
                 *                options.dialogSize - bootstrap postfix for dialog size, e.g. "sm", "m";
                 *                options.progressType - bootstrap postfix for progress bar type, e.g. "success", "warning".
                 */
                show: function (message, options) {
                    // Assigning defaults
                    if (typeof options === 'undefined') {
                        options = {};
                    }
                    if (typeof message === 'undefined') {
                        message = 'Loading';
                    }
                    var settings = $.extend({
                        dialogSize: 'm',
                        progressType: '',
                        onHide: null // This callback runs after the dialog was hidden
                    }, options);
        
                    // Configuring dialog
                    $dialog.find('.modal-dialog').attr('class', 'modal-dialog').addClass('modal-' + settings.dialogSize);
                    $dialog.find('.progress-bar').attr('class', 'progress-bar');
                    if (settings.progressType) {
                        $dialog.find('.progress-bar').addClass('progress-bar-' + settings.progressType);
                    }
                    $dialog.find('h3').text(message);
                    // Adding callbacks
                    if (typeof settings.onHide === 'function') {
                        $dialog.off('hidden.bs.modal').on('hidden.bs.modal', function (e) {
                            settings.onHide.call($dialog);
                        });
                    }
                    // Opening dialog
                    $dialog.modal();
                },
                /**
                 * Closes dialog
                 */
                hide: function () {
                    $dialog.modal('hide');
                }
            };
        
        })(jQuery);
        
    </script>
    </body>

	<?php require 'template/footer.php'; ?>
</html>